<a href="https://colab.research.google.com/github/kabirNahata/Learning-journey/blob/main/EDA_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Step 1: Import Python Libraries**

Pandas and Numpy have been used for Data Manipulation and numerical Calculations

Matplotlib and Seaborn have been used for Data visualizations.

In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport

**Step 2: Reading Dataset**

In [127]:
data = pd.read_csv("used_cars_data.csv")

In [128]:
data_report = ProfileReport(data, title="Used Cars Data Report")
report = data_report.to_file("used_cars_data_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]
 14%|█▍        | 2/14 [00:00<00:02,  5.24it/s]
 36%|███▌      | 5/14 [00:00<00:00, 11.64it/s]
 50%|█████     | 7/14 [00:00<00:00, 11.01it/s]
 64%|██████▍   | 9/14 [00:01<00:00,  8.68it/s]
100%|██████████| 14/14 [00:01<00:00, 12.11it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Analyzing the Data

shape – shape will display the number of observations(rows) and features(columns) in the dataset

In [129]:
data.shape

(7253, 14)

head() will display the top 5 observations of the dataset

In [130]:
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

tail() will display the last 5 observations of the dataset

In [131]:
data.tail()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

info() helps to understand the data type and information about data, including the number of records in each column, data having null or not null, Data type, the memory usage of the dataset

In [132]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   object
 2   Location           7253 non-null   object
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   object
 6   Transmission       7253 non-null   object
 7   Owner_Type         7253 non-null   object
 8   Mileage            7251 non-null   object
 9   Engine             7207 non-null   object
 10  Power              7207 non-null   object
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   object
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 793.4+ KB

nunique() based on several unique values in each column and the data description, we can identify the continuous and categorical columns in the data. Duplicated data can be handled or removed based on further analysis

In [133]:
data.nunique()

S.No.                7253
Name                 2041
Location               11
Year                   23
Kilometers_Driven    3660
Fuel_Type               5
Transmission            2
Owner_Type              4
Mileage               450
Engine                150
Power                 386
Seats                   9
New_Price             625
Price                1373
dtype: int64

isnull() is widely been in all pre-processing steps to identify null values in the data

In our example, data.isnull().sum() is used to get the number of missing records in each column

In [134]:
data.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

The below code helps to calculate the percentage of missing values in each column

In [135]:
data.isnull().sum()/(len((data)))*100

S.No.                 0.000000
Name                  0.000000
Location              0.000000
Year                  0.000000
Kilometers_Driven     0.000000
Fuel_Type             0.000000
Transmission          0.000000
Owner_Type            0.000000
Mileage               0.027575
Engine                0.634220
Power                 0.634220
Seats                 0.730732
New_Price            86.129877
Price                17.013650
dtype: float64

The percentage of missing values for the columns New_Price and Price is ~86% and ~17%, respectively.

**Step 3: Data Reduction**

Some columns or variables can be dropped if they do not add value to our analysis.

In our dataset, the column S.No have only ID values, assuming they don’t have any predictive power to predict the dependent variable.

In [136]:
# Remove S.No. column from data
data = data.drop(['S.No.'], axis = 1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   object
 1   Location           7253 non-null   object
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   object
 5   Transmission       7253 non-null   object
 6   Owner_Type         7253 non-null   object
 7   Mileage            7251 non-null   object
 8   Engine             7207 non-null   object
 9   Power              7207 non-null   object
 10  Seats              7200 non-null   float64
 11  New_Price          1006 non-null   object
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(2), object(9)
memory usage: 736.8+ KB

We start our Feature Engineering as we need to add some columns required for analysis.

**Step 4: Feature Engineering**

Feature engineering refers to the process of using domain knowledge to select and transform the most relevant variables from raw data when creating a predictive model using machine learning or statistical modeling. The main goal of Feature engineering is to create meaningful data from raw data.

**Step 5: Creating Features**

It would be difficult to find the car’s age if it is in year format as the Age of the car is a contributing factor to Car Price.

Introducing a new column, “Car_Age” to know the age of the car

In [137]:
from datetime import date
date.today().year
data['Car_Age']=date.today().year-data['Year']
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,15
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,10
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,14
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,13
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,12

Since car names will not be great predictors of the price in our current data. But we can process this column to extract important information using brand and Model names. Let’s split the name and introduce new variables “Brand” and “Model”

In [138]:
data['Brand'] = data.Name.str.split().str.get(0)

In [139]:
data['Model'] = data.Name.str.split().str.get(1) + data.Name.str.split().str.get(2)

In [140]:
data[['Name','Brand','Model']]

,Name,Brand,Model
0,Maruti Wagon R LXI CNG,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Hyundai,Creta1.6
2,Honda Jazz V,Honda,JazzV
3,Maruti Ertiga VDI,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Audi,A4New
...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Volkswagen,VentoDiesel
7249,Volkswagen Polo GT TSI,Volkswagen,PoloGT
7250,Nissan Micra Diesel XV,Nissan,MicraDiesel
7251,Volkswagen Polo GT TSI,Volkswagen,PoloGT
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Mercedes-Benz,E-Class2009-2013

**Step 6: Data Cleaning/Wrangling**

Some names of the variables are not relevant and not easy to understand. Some data may have data entry errors, and some variables may need data type conversion. We need to fix this issue in the data.

In the example, The brand name ‘Isuzu’ ‘ISUZU’ and ‘Mini’ and ‘Land’ looks incorrect. This needs to be corrected

In [141]:
print(data.Brand.unique())
print(data.Brand.nunique())

['Maruti' 'Hyundai' 'Honda' 'Audi' 'Nissan' 'Toyota' 'Volkswagen' 'Tata'
 'Land' 'Mitsubishi' 'Renault' 'Mercedes-Benz' 'BMW' 'Mahindra' 'Ford'
 'Porsche' 'Datsun' 'Jaguar' 'Volvo' 'Chevrolet' 'Skoda' 'Mini' 'Fiat'
 'Jeep' 'Smart' 'Ambassador' 'Isuzu' 'ISUZU' 'Force' 'Bentley'
 'Lamborghini' 'Hindustan' 'OpelCorsa']
33

There are brand names that are not making sense, to fix them

In [142]:
searchfor = ['Isuzu' ,'ISUZU','Mini','Land']
data[data.Brand.str.contains('|'.join(searchfor))].head(5)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,27.00,11,Land,RoverRange
14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.0 kmpl,2179 CC,115 bhp,5.0,NaN,17.50,13,Land,RoverFreelander
176,Mini Countryman Cooper D,Jaipur,2017,8525,Diesel,Automatic,Second,16.6 kmpl,1998 CC,112 bhp,5.0,NaN,23.00,8,Mini,CountrymanCooper
191,Land Rover Range Rover 2.2L Dynamic,Coimbatore,2018,36091,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,55.76,7,Land,RoverRange
228,Mini Cooper Convertible S,Kochi,2017,26327,Petrol,Automatic,First,16.82 kmpl,1998 CC,189.08 bhp,4.0,44.28 Lakh,35.67,8,Mini,CooperConvertible

In [143]:
data["Brand"].replace({"ISUZU": "Isuzu", "Mini": "Mini Cooper","Land":"Land Rover"}, inplace=True)

looking at the first row

In [144]:
data.iloc[0]

Name                 Maruti Wagon R LXI CNG
Location                             Mumbai
Year                                   2010
Kilometers_Driven                     72000
Fuel_Type                               CNG
Transmission                         Manual
Owner_Type                            First
Mileage                          26.6 km/kg
Engine                               998 CC
Power                             58.16 bhp
Seats                                   5.0
New_Price                               NaN
Price                                  1.75
Car_Age                                  15
Brand                                Maruti
Model                                WagonR
Name: 0, dtype: object

value_count() counts the unique value for given column

In [145]:
data.Brand.value_counts()

Brand
Maruti           1444
Hyundai          1340
Honda             743
Toyota            507
Mercedes-Benz     380
Volkswagen        374
Ford              351
Mahindra          331
BMW               312
Audi              285
Tata              228
Skoda             202
Renault           170
Chevrolet         151
Nissan            117
Land Rover         67
Jaguar             48
Fiat               38
Mitsubishi         36
Mini Cooper        31
Volvo              28
Porsche            19
Jeep               19
Datsun             17
Isuzu               5
Force               3
Bentley             2
Ambassador          1
Smart               1
Lamborghini         1
Hindustan           1
OpelCorsa           1
Name: count, dtype: int64

In [146]:
data.Brand.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
7248    False
7249    False
7250    False
7251    False
7252    False
Name: Brand, Length: 7253, dtype: bool

duplicated() checkes for duplicated value according row by row

In [147]:
data.Brand.duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
7248     True
7249     True
7250     True
7251     True
7252     True
Name: Brand, Length: 7253, dtype: bool

In [148]:
variable = data.Brand.value_counts()

In [149]:
type(variable)

pandas.core.series.Series

In [150]:
variable["Maruti"]+2

np.int64(1446)

In [151]:
data.describe(include = "all")

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
count,7253,7253,7253.000000,7.253000e+03,7253,7253,7253,7251,7207,7207,7200.000000,1006,6019.000000,7253.000000,7253,7252
unique,2041,11,NaN,NaN,5,2,4,450,150,386,NaN,625,NaN,NaN,32,726
top,Mahindra XUV500 W8 2WD,Mumbai,NaN,NaN,Diesel,Manual,First,17.0 kmpl,1197 CC,74 bhp,NaN,95.13 Lakh,NaN,NaN,Maruti,SwiftDzire
freq,55,949,NaN,NaN,3852,5204,5952,207,732,280,NaN,6,NaN,NaN,1444,189
mean,NaN,NaN,2013.365366,5.869906e+04,NaN,NaN,NaN,NaN,NaN,NaN,5.279722,NaN,9.479468,11.634634,NaN,NaN
std,NaN,NaN,3.254421,8.442772e+04,NaN,NaN,NaN,NaN,NaN,NaN,0.811660,NaN,11.187917,3.254421,NaN,NaN
min,NaN,NaN,1996.000000,1.710000e+02,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.440000,6.000000,NaN,NaN
25%,NaN,NaN,2011.000000,3.400000e+04,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,3.500000,9.000000,NaN,NaN
50%,NaN,NaN,2014.000000,5.341600e+04,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,5.640000,11.000000,NaN,NaN
75%,NaN,NaN,2016.000000,7.300000e+04,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,9.950000,14.000000,NaN,NaN
max,NaN,NaN,2019.000000,6.500000e+06,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,160.000000,29.000000,NaN,NaN

In [152]:
data['Year']

0       2010
1       2015
2       2011
3       2012
4       2013
        ...
7248    2011
7249    2015
7250    2012
7251    2013
7252    2014
Name: Year, Length: 7253, dtype: int64

In [153]:
data.describe()

              Year  Kilometers_Driven        Seats        Price      Car_Age
count  7253.000000       7.253000e+03  7200.000000  6019.000000  7253.000000
mean   2013.365366       5.869906e+04     5.279722     9.479468    11.634634
std       3.254421       8.442772e+04     0.811660    11.187917     3.254421
min    1996.000000       1.710000e+02     0.000000     0.440000     6.000000
25%    2011.000000       3.400000e+04     5.000000     3.500000     9.000000
50%    2014.000000       5.341600e+04     5.000000     5.640000    11.000000
75%    2016.000000       7.300000e+04     5.000000     9.950000    14.000000
max    2019.000000       6.500000e+06    10.000000   160.000000    29.000000

In [154]:
data.dtypes

Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
New_Price             object
Price                float64
Car_Age                int64
Brand                 object
Model                 object
dtype: object

In [155]:
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,10,Hyundai,Creta1.6
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,14,Honda,JazzV
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,12,Audi,A4New

# change new price value to float, remove the string
# change seat into int from float

In [156]:
import numpy as np

In [157]:
temp_data = data.copy()

In [158]:
np.isfinite(temp_data.Seats)

0       True
1       True
2       True
3       True
4       True
        ...
7248    True
7249    True
7250    True
7251    True
7252    True
Name: Seats, Length: 7253, dtype: bool

In [159]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
6.0       38
2.0       18
10.0       8
9.0        3
0.0        1
Name: count, dtype: int64

In [160]:
temp_data[temp_data.Seats==0]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
3999,Audi A4 3.2 FSI Tiptronic Quattro,Hyderabad,2012,125000,Petrol,Automatic,First,10.5 kmpl,3197 CC,null bhp,0.0,NaN,18.0,13,Audi,A43.2

In [161]:
temp_data.Seats[3999] = 2

<ipython-input-161-6704346f2f04>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  temp_data.Seats[3999] = 2
<ipython-input-161-6704346f2f04>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data.Seats[3999] = 2

In [162]:
temp_data.iloc[3999]

Name                 Audi A4 3.2 FSI Tiptronic Quattro
Location                                     Hyderabad
Year                                              2012
Kilometers_Driven                               125000
Fuel_Type                                       Petrol
Transmission                                 Automatic
Owner_Type                                       First
Mileage                                      10.5 kmpl
Engine                                         3197 CC
Power                                         null bhp
Seats                                              2.0
New_Price                                          NaN
Price                                             18.0
Car_Age                                             13
Brand                                             Audi
Model                                            A43.2
Name: 3999, dtype: object

index 3999, seats value 0 change into 2

In [163]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
6.0       38
2.0       19
10.0       8
9.0        3
Name: count, dtype: int64

Update original dataframe using temporary dataframe

In [164]:
temp_data.Seats

0       5.0
1       5.0
2       5.0
3       7.0
4       5.0
       ...
7248    5.0
7249    5.0
7250    5.0
7251    5.0
7252    5.0
Name: Seats, Length: 7253, dtype: float64

In [165]:
temp_data.Seats = data.Seats

In [166]:
temp_data.Seats

0       5.0
1       5.0
2       5.0
3       7.0
4       5.0
       ...
7248    5.0
7249    5.0
7250    5.0
7251    5.0
7252    5.0
Name: Seats, Length: 7253, dtype: float64

In [167]:
temp_data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,10,Hyundai,Creta1.6
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,14,Honda,JazzV
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,12,Audi,A4New

In [168]:
temp_data.Seats.unique()

array([ 5.,  7.,  8.,  4.,  6.,  2., nan, 10.,  9.,  0.])

In [169]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
6.0       38
2.0       18
10.0       8
9.0        3
0.0        1
Name: count, dtype: int64

In [170]:
temp_data.Seats[3999] = 2

<ipython-input-170-6704346f2f04>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data.Seats[3999] = 2

In [171]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
6.0       38
2.0       19
10.0       8
9.0        3
Name: count, dtype: int64

In [172]:
temp_data[temp_data.Seats.isna()]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
194,Honda City 1.5 GXI,Ahmedabad,2007,60006,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,2.95,18,Honda,City1.5
208,Maruti Swift 1.3 VXi,Kolkata,2010,42001,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,2.11,15,Maruti,Swift1.3
229,Ford Figo Diesel,Bangalore,2015,70436,Diesel,Manual,First,0.0 kmpl,1498 CC,99 bhp,NaN,NaN,3.60,10,Ford,FigoDiesel
733,Maruti Swift 1.3 VXi,Chennai,2006,97800,Petrol,Manual,Third,16.1 kmpl,NaN,NaN,NaN,NaN,1.75,19,Maruti,Swift1.3
749,Land Rover Range Rover 3.0 D,Mumbai,2008,55001,Diesel,Automatic,Second,0.0 kmpl,NaN,NaN,NaN,NaN,26.50,17,Land Rover,RoverRange
1294,Honda City 1.3 DX,Delhi,2009,55005,Petrol,Manual,First,12.8 kmpl,NaN,NaN,NaN,NaN,3.20,16,Honda,City1.3
1327,Maruti Swift 1.3 ZXI,Hyderabad,2015,50295,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,5.80,10,Maruti,Swift1.3
1385,Honda City 1.5 GXI,Pune,2004,115000,Petrol,Manual,Second,0.0 kmpl,NaN,NaN,NaN,NaN,1.50,21,Honda,City1.5
1460,Land Rover Range Rover Sport 2005 2012 Sport,Coimbatore,2008,69078,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,40.88,17,Land Rover,RoverRange
1917,Honda City 1.5 EXI,Jaipur,2005,88000,Petrol,Manual,Second,13.0 kmpl,1493 CC,100 bhp,NaN,NaN,1.70,20,Honda,City1.5
2074,Maruti Swift 1.3 LXI,Pune,2011,24255,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,3.15,14,Maruti,Swift1.3
2096,Hyundai Santro LP zipPlus,Coimbatore,2004,52146,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,1.93,21,Hyundai,SantroLP
2264,Toyota Etios Liva V,Pune,2012,24500,Petrol,Manual,Second,18.3 kmpl,NaN,NaN,NaN,NaN,2.95,13,Toyota,EtiosLiva
2325,Maruti Swift 1.3 VXI ABS,Pune,2015,67000,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,4.70,10,Maruti,Swift1.3
2335,Maruti Swift 1.3 VXi,Mumbai,2007,55000,Petrol,Manual,Second,16.1 kmpl,NaN,NaN,NaN,NaN,1.75,18,Maruti,Swift1.3
2369,Maruti Estilo LXI,Chennai,2008,56000,Petrol,Manual,Second,19.5 kmpl,1061 CC,null bhp,NaN,NaN,1.50,17,Maruti,EstiloLXI
2530,BMW 5 Series 520d Sedan,Kochi,2014,64158,Diesel,Automatic,First,18.48 kmpl,NaN,NaN,NaN,NaN,17.89,11,BMW,5Series
2542,Hyundai Santro GLS II - Euro II,Bangalore,2011,65000,Petrol,Manual,Second,0.0 kmpl,NaN,NaN,NaN,NaN,3.15,14,Hyundai,SantroGLS
2623,BMW 5 Series 520d Sedan,Pune,2012,95000,Diesel,Automatic,Second,18.48 kmpl,NaN,NaN,NaN,NaN,18.00,13,BMW,5Series
2668,Maruti Swift 1.3 VXi,Kolkata,2014,32986,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,4.24,11,Maruti,Swift1.3
2737,Maruti Wagon R Vx,Jaipur,2001,200000,Petrol,Manual,First,12.0 kmpl,NaN,NaN,NaN,NaN,0.70,24,Maruti,WagonR
2780,Hyundai Santro GLS II - Euro II,Pune,2009,100000,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,1.60,16,Hyundai,SantroGLS
2842,Hyundai Santro GLS II - Euro II,Bangalore,2012,43000,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,3.25,13,Hyundai,SantroGLS
3272,BMW 5 Series 520d Sedan,Mumbai,2008,81000,Diesel,Automatic,Second,18.48 kmpl,NaN,NaN,NaN,NaN,10.50,17,BMW,5Series
3404,Maruti Swift 1.3 VXi,Jaipur,2006,125000,Petrol,Manual,Fourth & Above,16.1 kmpl,NaN,NaN,NaN,NaN,2.35,19,Maruti,Swift1.3
3520,BMW 5 Series 520d Sedan,Delhi,2012,90000,Diesel,Automatic,First,18.48 kmpl,NaN,NaN,NaN,NaN,14.50,13,BMW,5Series
3522,Hyundai Santro GLS II - Euro II,Kochi,2012,66400,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,2.66,13,Hyundai,SantroGLS
3800,Ford Endeavour Hurricane LE,Mumbai,2012,129000,Diesel,Automatic,First,12.8 kmpl,2953 CC,null bhp,NaN,NaN,7.00,13,Ford,EndeavourHurricane
3810,Honda CR-V AT With Sun Roof,Kolkata,2013,27000,Petrol,Automatic,First,14.0 kmpl,NaN,NaN,NaN,NaN,11.99,12,Honda,CR-VAT
3882,Maruti Estilo LXI,Kolkata,2010,40000,Petrol,Manual,Second,19.5 kmpl,1061 CC,null bhp,NaN,NaN,2.50,15,Maruti,EstiloLXI
4011,Fiat Punto 1.3 Emotion,Pune,2011,45271,Diesel,Manual,First,20.3 kmpl,NaN,NaN,NaN,NaN,2.60,14,Fiat,Punto1.3
4152,Land Rover Range Rover 3.0 D,Mumbai,2003,75000,Diesel,Automatic,Second,0.0 kmpl,NaN,NaN,NaN,NaN,16.11,22,Land Rover,RoverRange
4229,Hyundai Santro Xing XG,Bangalore,2005,79000,Petrol,Manual,Second,17.0 kmpl,NaN,NaN,NaN,NaN,1.65,20,Hyundai,SantroXing
4577,BMW 5 Series 520d Sedan,Delhi,2012,72000,Diesel,Automatic,Third,18.48 kmpl,NaN,NaN,NaN,NaN,13.85,13,BMW,5Series
4604,Honda Jazz Select Edition,Pune,2011,98000,Petrol,Manual,First,16.7 kmpl,NaN,NaN,NaN,NaN,3.15,14,Honda,JazzSelect
4697,Fiat Punto 1.2 Dynamic,Kochi,2017,17941,Petrol,Manual,First,15.7 kmpl,NaN,NaN,NaN,NaN,3.93,8,Fiat,Punto1.2
4712,Hyundai Santro Xing XG,Pune,2003,80000,Petrol,Manual,Second,17.0 kmpl,NaN,NaN,NaN,NaN,0.90,22,Hyundai,SantroXing
4952,Fiat Punto 1.4 Emotion,Kolkata,2010,47000,Petrol,Manual,First,14.6 kmpl,NaN,NaN,NaN,NaN,1.49,15,Fiat,Punto1.4
5015,Maruti Swift 1.3 VXi,Delhi,2006,63000,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,1.60,19,Maruti,Swift1.3
5185,Maruti Swift 1.3 LXI,Delhi,2012,52000,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,3.65,13,Maruti,Swift1.3
5270,Honda City 1.5 GXI,Bangalore,2002,53000,Petrol,Manual,Second,0.0 kmpl,NaN,NaN,NaN,NaN,1.85,23,Honda,City1.5
5893,Maruti Estilo LXI,Chennai,2008,51000,Petrol,Manual,Second,19.5 kmpl,1061 CC,null bhp,NaN,NaN,1.75,17,Maruti,EstiloLXI
6042,Skoda Laura 1.8 TSI Ambition,Bangalore,2009,72000,Petrol,Manual,Second,17.5 kmpl,NaN,NaN,NaN,NaN,NaN,16,Skoda,Laura1.8
6541,Toyota Etios Liva Diesel TRD Sportivo,Bangalore,2012,56600,Diesel,Manual,First,23.59 kmpl,NaN,NaN,NaN,NaN,NaN,13,Toyota,EtiosLiva
6544,Hyundai i20 new Sportz AT 1.4,Bangalore,2012,58000,Petrol,Automatic,Second,15.0 kmpl,NaN,NaN,NaN,NaN,NaN,13,Hyundai,i20new
6633,Mahindra TUV 300 P4,Kolkata,2016,27000,Diesel,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,NaN,9,Mahindra,TUV300
6643,BMW 5 Series 520d Sedan,Bangalore,2009,150000,Diesel,Automatic,Second,18.48 kmpl,NaN,NaN,NaN,NaN,NaN,16,BMW,5Series
6651,Maruti Swift 1.3 VXi,Kolkata,2015,36009,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,NaN,10,Maruti,Swift1.3
6677,Fiat Punto 1.4 Emotion,Jaipur,2010,65000,Petrol,Manual,Third,14.6 kmpl,NaN,NaN,NaN,NaN,NaN,15,Fiat,Punto1.4
6685,Maruti Swift 1.3 VXi,Pune,2010,115000,Petrol,Manual,Second,16.1 kmpl,NaN,NaN,NaN,NaN,NaN,15,Maruti,Swift1.3
6880,BMW 5 Series 520d Sedan,Chennai,2009,95000,Diesel,Automatic,Second,18.48 kmpl,NaN,NaN,NaN,NaN,NaN,16,BMW,5Series
6902,Toyota Etios Liva V,Kochi,2012,59311,Petrol,Manual,First,18.3 kmpl,NaN,NaN,NaN,NaN,NaN,13,Toyota,EtiosLiva
6957,Honda Jazz 2020 Petrol,Kochi,2019,11574,Petrol,Manual,First,0.0 kmpl,1199 CC,88.7 bhp,NaN,NaN,NaN,6,Honda,Jazz2020

In [173]:
temp_data[temp_data.Seats.isna()] = 2

In [174]:
temp_data.Seats.unique()

array([ 5.,  7.,  8.,  4.,  6.,  2., 10.,  9.])

In [175]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
2.0       72
6.0       38
10.0       8
9.0        3
Name: count, dtype: int64

In [176]:
temp_data.describe()

              Year  Kilometers_Driven        Seats        Price      Car_Age
count  7253.000000       7.253000e+03  7253.000000  6030.000000  7253.000000
mean   1998.693230       5.820014e+04     5.256032     9.436831    11.538674
std     171.352255       8.452090e+04     0.854206    11.176640     3.325560
min       2.000000       2.000000e+00     2.000000     0.440000     2.000000
25%    2011.000000       3.301600e+04     5.000000     3.490000     9.000000
50%    2014.000000       5.300000e+04     5.000000     5.600000    11.000000
75%    2016.000000       7.300000e+04     5.000000     9.897500    13.000000
max    2019.000000       6.500000e+06    10.000000   160.000000    29.000000

In [177]:
temp_data.Seats.dtypes

dtype('float64')

In [178]:
temp_data.Seats = temp_data.Seats.astype(int)

In [179]:
temp_data.Seats.dtypes

dtype('int64')

In [180]:
temp_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   object
 1   Location           7253 non-null   object
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   object
 5   Transmission       7253 non-null   object
 6   Owner_Type         7253 non-null   object
 7   Mileage            7251 non-null   object
 8   Engine             7253 non-null   object
 9   Power              7253 non-null   object
 10  Seats              7253 non-null   int64
 11  New_Price          1059 non-null   object
 12  Price              6030 non-null   float64
 13  Car_Age            7253 non-null   int64
 14  Brand              7253 non-null   object
 15  Model              7252 non-null   object
dtypes: float64(1), int64(4), object(11)
memory usage: 906.8+ KB

In [181]:
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,10,Hyundai,Creta1.6
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,14,Honda,JazzV
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,12,Audi,A4New

In [182]:
data.New_Price.value_counts()

New_Price
95.13 Lakh    6
4.78 Lakh     6
33.36 Lakh    6
63.71 Lakh    6
20.74 Lakh    5
             ..
23.29 Lakh    1
13.08 Lakh    1
4.02 Lakh     1
66.71 Lakh    1
15.11 Lakh    1
Name: count, Length: 625, dtype: int64

In [183]:
data.New_Price.nunique()

625

In [184]:
data.shape

(7253, 16)

In [185]:
temp_data[temp_data.New_Price.isna()]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5,NaN,12.50,10,Hyundai,Creta1.6
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5,NaN,17.74,12,Audi,A4New
5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5,NaN,2.35,13,Hyundai,EONLPG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5,NaN,NaN,14,Volkswagen,VentoDiesel
7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5,NaN,NaN,10,Volkswagen,PoloGT
7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5,NaN,NaN,13,Nissan,MicraDiesel
7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5,NaN,NaN,12,Volkswagen,PoloGT
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5,NaN,NaN,11,Mercedes-Benz,E-Class2009-2013

In [186]:
temp_data.dtypes

Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                  int64
New_Price             object
Price                float64
Car_Age                int64
Brand                 object
Model                 object
dtype: object

In [187]:
temp_data.Fuel_Type.value_counts()

Fuel_Type
Diesel      3838
Petrol      3286
CNG           62
2             53
LPG           12
Electric       2
Name: count, dtype: int64

In [189]:
temp_data.Brand.value_counts()

Brand
Maruti           1428
Hyundai          1332
Honda             735
Toyota            504
Mercedes-Benz     380
Volkswagen        374
Ford              349
Mahindra          330
BMW               305
Audi              285
Tata              228
Skoda             201
Renault           170
Chevrolet         151
Nissan            117
Land Rover         64
2                  53
Jaguar             48
Mitsubishi         36
Fiat               34
Mini Cooper        31
Volvo              28
Porsche            19
Jeep               19
Datsun             17
Isuzu               5
Force               3
Bentley             2
Ambassador          1
Smart               1
Lamborghini         1
Hindustan           1
OpelCorsa           1
Name: count, dtype: int64

Maruti and Hyundai, disel and petrol - target

In [190]:
len(temp_data[temp_data["Brand"]=='Maruti'][temp_data["Fuel_Type"]=='Petrol'])

<ipython-input-190-f913318a77de>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(temp_data[temp_data["Brand"]=='Maruti'][temp_data["Fuel_Type"]=='Petrol'])

819

In [191]:
len(temp_data[temp_data["Brand"]=='Maruti'][temp_data["Fuel_Type"]=='Diesel'])

<ipython-input-191-859b4cbd4a8e>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(temp_data[temp_data["Brand"]=='Maruti'][temp_data["Fuel_Type"]=='Diesel'])

549

In [192]:
len(temp_data[(temp_data["Brand"]=='Maruti') & (temp_data["Fuel_Type"]!='Diesel') & (temp_data["Fuel_Type"]!='Petrol')])

60

In [193]:
len(temp_data[(temp_data["Brand"]=='Maruti') & (temp_data["Fuel_Type"]=='Diesel') & (temp_data["Fuel_Type"]=='Petrol')])

0

In [194]:
maruti = temp_data[(temp_data["Brand"]=='Maruti') & ((temp_data["Fuel_Type"]=='Petrol') | (temp_data["Fuel_Type"]=='Diesel'))]

In [195]:
maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7,NaN,6.00,13,Maruti,ErtigaVDI
10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5,10.65 Lakh,9.95,7,Maruti,CiazZeta
12,Maruti Swift VDI BSIV,Jaipur,2015,64424,Diesel,Manual,First,25.2 kmpl,1248 CC,74 bhp,5,NaN,5.60,10,Maruti,SwiftVDI
17,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5,NaN,5.99,8,Maruti,SwiftDDiS
21,Maruti S Cross DDiS 200 Alpha,Bangalore,2015,55392,Diesel,Manual,Second,23.65 kmpl,1248 CC,88.5 bhp,5,NaN,8.25,10,Maruti,SCross
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7210,Maruti Vitara Brezza VDi Option,Jaipur,2017,19000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,NaN,NaN,8,Maruti,VitaraBrezza
7218,Maruti Vitara Brezza ZDi Plus AMT,Mumbai,2018,3800,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5,12.46 Lakh,NaN,7,Maruti,VitaraBrezza
7220,Maruti Dzire AMT VDI,Delhi,2017,14300,Diesel,Automatic,First,28.4 kmpl,1248 CC,73.75 bhp,5,9.11 Lakh,NaN,8,Maruti,DzireAMT
7222,Maruti Celerio VXI AT,Chennai,2015,31717,Petrol,Automatic,First,23.1 kmpl,998 CC,67.04 bhp,5,NaN,NaN,10,Maruti,CelerioVXI
7235,Maruti Vitara Brezza ZDi,Kochi,2017,21380,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,10.57 Lakh,NaN,8,Maruti,VitaraBrezza

#..... need to add disel also, but in string form, ex: a + b

In [196]:
maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7,NaN,6.00,13,Maruti,ErtigaVDI
10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5,10.65 Lakh,9.95,7,Maruti,CiazZeta
12,Maruti Swift VDI BSIV,Jaipur,2015,64424,Diesel,Manual,First,25.2 kmpl,1248 CC,74 bhp,5,NaN,5.60,10,Maruti,SwiftVDI
17,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5,NaN,5.99,8,Maruti,SwiftDDiS
21,Maruti S Cross DDiS 200 Alpha,Bangalore,2015,55392,Diesel,Manual,Second,23.65 kmpl,1248 CC,88.5 bhp,5,NaN,8.25,10,Maruti,SCross
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7210,Maruti Vitara Brezza VDi Option,Jaipur,2017,19000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,NaN,NaN,8,Maruti,VitaraBrezza
7218,Maruti Vitara Brezza ZDi Plus AMT,Mumbai,2018,3800,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5,12.46 Lakh,NaN,7,Maruti,VitaraBrezza
7220,Maruti Dzire AMT VDI,Delhi,2017,14300,Diesel,Automatic,First,28.4 kmpl,1248 CC,73.75 bhp,5,9.11 Lakh,NaN,8,Maruti,DzireAMT
7222,Maruti Celerio VXI AT,Chennai,2015,31717,Petrol,Automatic,First,23.1 kmpl,998 CC,67.04 bhp,5,NaN,NaN,10,Maruti,CelerioVXI
7235,Maruti Vitara Brezza ZDi,Kochi,2017,21380,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,10.57 Lakh,NaN,8,Maruti,VitaraBrezza

In [197]:
len(temp_data[temp_data["Brand"]=='Hyundai'][temp_data["Fuel_Type"]=='Petrol'])

<ipython-input-197-5ef9c209f835>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(temp_data[temp_data["Brand"]=='Hyundai'][temp_data["Fuel_Type"]=='Petrol'])

897

In [198]:
len(temp_data[temp_data["Brand"]=='Hyundai'][temp_data["Fuel_Type"]=='Diesel'])

<ipython-input-198-b4598829a9c6>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(temp_data[temp_data["Brand"]=='Hyundai'][temp_data["Fuel_Type"]=='Diesel'])

424

In [199]:
hyundai = temp_data[(temp_data["Brand"]=='Hyundai') & ((temp_data["Fuel_Type"]=='Petrol') | (temp_data["Fuel_Type"]=='Diesel'))]

Createing a dataframe for maruti with petrol and diesel

In [200]:
temp_data[temp_data['Kilometers_Driven']==6500000]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
2328,BMW X5 xDrive 30d M Sport,Chennai,2017,6500000,Diesel,Automatic,First,15.97 kmpl,2993 CC,258 bhp,5,NaN,65.0,8,BMW,X5xDrive

In [201]:
hyundai.describe()

              Year  Kilometers_Driven        Seats        Price      Car_Age
count  1321.000000        1321.000000  1321.000000  1091.000000  1321.000000
mean   2013.514005       51363.423164     5.028766     5.383905    11.485995
std       3.295083       34168.354019     0.238218     3.315572     3.295083
min    2001.000000        1000.000000     5.000000     0.450000     6.000000
25%    2012.000000       30529.000000     5.000000     3.105000     9.000000
50%    2014.000000       47200.000000     5.000000     4.650000    11.000000
75%    2016.000000       65461.000000     5.000000     6.500000    13.000000
max    2019.000000      620000.000000     7.000000    23.000000    24.000000

In [202]:
hyundai.isnull()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
1,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7234,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
7236,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
7242,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
7246,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
7247,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False

In [203]:
hyundai.to_csv('hyundai.csv')

In [204]:
maruti.to_csv("maruti.csv")

In [205]:
ProfileReport(hyundai,title = "Hyundai Report").to_file('hyundai_report.html')

/usr/local/lib/python3.11/dist-packages/ydata_profiling/utils/dataframe.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"index": "df_index"}, inplace=True)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]
 31%|███▏      | 5/16 [00:00<00:00, 40.29it/s]
 62%|██████▎   | 10/16 [00:00<00:00, 39.50it/s]
100%|██████████| 16/16 [00:00<00:00, 44.65it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [206]:
ProfileReport(maruti,title = "Maruti Report").to_file('maruti_report.html')

/usr/local/lib/python3.11/dist-packages/ydata_profiling/utils/dataframe.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"index": "df_index"}, inplace=True)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]
 31%|███▏      | 5/16 [00:00<00:00, 39.92it/s]
 56%|█████▋    | 9/16 [00:00<00:00, 30.41it/s]
100%|██████████| 16/16 [00:00<00:00, 38.35it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [207]:
temp_data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5,NaN,12.50,10,Hyundai,Creta1.6
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5,8.61 Lakh,4.50,14,Honda,JazzV
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5,NaN,17.74,12,Audi,A4New

maruti,hyundai, diesel, petrol,age,kilometer,transmission-maunaul, owner- first, mileage, engine,power,seat-5,price-missing??

kilometer range 50,000 - 55,000

In [216]:
kilometer_maruti = maruti[(maruti.Kilometers_Driven>=50000) & (maruti.Kilometers_Driven<=55000)]

In [215]:
kilometer_maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Petrol,Manual,Second,20.92 kmpl,998 CC,67.1 bhp,5,NaN,2.75,12,Maruti,AltoK10
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,11.12 Lakh,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9 kmpl,1248 CC,74 bhp,5,NaN,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8 kmpl,1248 CC,75 bhp,5,NaN,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,9.96 Lakh,7.50,9,Maruti,VitaraBrezza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7 kmpl,796 CC,46.3 bhp,5,NaN,NaN,15,Maruti,AltoLXI
6934,Maruti A-Star Vxi,Chennai,2009,53000,Petrol,Manual,Second,19.0 kmpl,998 CC,66.1 bhp,5,NaN,NaN,16,Maruti,A-StarVxi
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0 kmpl,1586 CC,104.68 bhp,5,NaN,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4 kmpl,1197 CC,81.80 bhp,5,NaN,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5,NaN,NaN,14,Maruti,WagonR

In [217]:
kilometer_maruti['Mileage'] = kilometer_maruti.Mileage.str.split().str.get(0)

<ipython-input-217-bd07aa93b34f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kilometer_maruti['Mileage'] = kilometer_maruti.Mileage.str.split().str.get(0)

In [218]:
kilometer_maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Petrol,Manual,Second,20.92,998 CC,67.1 bhp,5,NaN,2.75,12,Maruti,AltoK10
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248 CC,88.5 bhp,5,11.12 Lakh,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248 CC,74 bhp,5,NaN,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248 CC,75 bhp,5,NaN,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248 CC,88.5 bhp,5,9.96 Lakh,7.50,9,Maruti,VitaraBrezza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796 CC,46.3 bhp,5,NaN,NaN,15,Maruti,AltoLXI
6934,Maruti A-Star Vxi,Chennai,2009,53000,Petrol,Manual,Second,19.0,998 CC,66.1 bhp,5,NaN,NaN,16,Maruti,A-StarVxi
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586 CC,104.68 bhp,5,NaN,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197 CC,81.80 bhp,5,NaN,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998 CC,67.1 bhp,5,NaN,NaN,14,Maruti,WagonR

In [219]:
kilometer_maruti['Engine'] = kilometer_maruti.Engine.str.split().str.get(0)

<ipython-input-219-3ab6d0396114>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kilometer_maruti['Engine'] = kilometer_maruti.Engine.str.split().str.get(0)

In [220]:
kilometer_maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Petrol,Manual,Second,20.92,998,67.1 bhp,5,NaN,2.75,12,Maruti,AltoK10
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5 bhp,5,11.12 Lakh,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248,74 bhp,5,NaN,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248,75 bhp,5,NaN,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5 bhp,5,9.96 Lakh,7.50,9,Maruti,VitaraBrezza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796,46.3 bhp,5,NaN,NaN,15,Maruti,AltoLXI
6934,Maruti A-Star Vxi,Chennai,2009,53000,Petrol,Manual,Second,19.0,998,66.1 bhp,5,NaN,NaN,16,Maruti,A-StarVxi
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586,104.68 bhp,5,NaN,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197,81.80 bhp,5,NaN,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998,67.1 bhp,5,NaN,NaN,14,Maruti,WagonR

In [221]:
kilometer_maruti['Power'] = kilometer_maruti.Power.str.split().str.get(0)

<ipython-input-221-6a5cd282b1aa>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kilometer_maruti['Power'] = kilometer_maruti.Power.str.split().str.get(0)

In [222]:
kilometer_maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Petrol,Manual,Second,20.92,998,67.1,5,NaN,2.75,12,Maruti,AltoK10
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5,5,11.12 Lakh,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248,74,5,NaN,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248,75,5,NaN,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5,5,9.96 Lakh,7.50,9,Maruti,VitaraBrezza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796,46.3,5,NaN,NaN,15,Maruti,AltoLXI
6934,Maruti A-Star Vxi,Chennai,2009,53000,Petrol,Manual,Second,19.0,998,66.1,5,NaN,NaN,16,Maruti,A-StarVxi
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586,104.68,5,NaN,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197,81.80,5,NaN,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998,67.1,5,NaN,NaN,14,Maruti,WagonR

In [227]:
kilometer_maruti = kilometer_maruti[(kilometer_maruti.Transmission == "Manual")]

In [228]:
kilometer_maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Petrol,Manual,Second,20.92,998,67.1,5,NaN,2.75,12,Maruti,AltoK10
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5,5,11.12 Lakh,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248,74,5,NaN,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248,75,5,NaN,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5,5,9.96 Lakh,7.50,9,Maruti,VitaraBrezza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796,46.3,5,NaN,NaN,15,Maruti,AltoLXI
6934,Maruti A-Star Vxi,Chennai,2009,53000,Petrol,Manual,Second,19.0,998,66.1,5,NaN,NaN,16,Maruti,A-StarVxi
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586,104.68,5,NaN,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197,81.80,5,NaN,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998,67.1,5,NaN,NaN,14,Maruti,WagonR

In [229]:
kilometer_maruti = kilometer_maruti[(kilometer_maruti.Owner_Type == "First")]
kilometer_maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5,5,11.12 Lakh,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248,74,5,NaN,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248,75,5,NaN,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5,5,9.96 Lakh,7.50,9,Maruti,VitaraBrezza
243,Maruti Ertiga VDI,Chennai,2013,52000,Diesel,Manual,First,20.77,1248,88.76,7,NaN,6.90,12,Maruti,ErtigaVDI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6588,Maruti Wagon R LXI,Kolkata,2014,54841,Petrol,Manual,First,22.5,998,67.04,5,4.75 Lakh,NaN,11,Maruti,WagonR
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796,46.3,5,NaN,NaN,15,Maruti,AltoLXI
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586,104.68,5,NaN,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197,81.80,5,NaN,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998,67.1,5,NaN,NaN,14,Maruti,WagonR

In [231]:
kilometer_maruti = kilometer_maruti[(kilometer_maruti.Seats == 5)]
kilometer_maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5,5,11.12 Lakh,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248,74,5,NaN,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248,75,5,NaN,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5,5,9.96 Lakh,7.50,9,Maruti,VitaraBrezza
403,Maruti Wagon R LXI BSIII,Pune,2013,53000,Petrol,Manual,First,14.0,1061,64,5,NaN,2.75,12,Maruti,WagonR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6588,Maruti Wagon R LXI,Kolkata,2014,54841,Petrol,Manual,First,22.5,998,67.04,5,4.75 Lakh,NaN,11,Maruti,WagonR
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796,46.3,5,NaN,NaN,15,Maruti,AltoLXI
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586,104.68,5,NaN,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197,81.80,5,NaN,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998,67.1,5,NaN,NaN,14,Maruti,WagonR

In [232]:
kilometer_maruti = kilometer_maruti.rename(columns={'Engine': 'Engine_CC'})
kilometer_maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine_CC,Power,Seats,New_Price,Price,Car_Age,Brand,Model
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5,5,11.12 Lakh,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248,74,5,NaN,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248,75,5,NaN,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5,5,9.96 Lakh,7.50,9,Maruti,VitaraBrezza
403,Maruti Wagon R LXI BSIII,Pune,2013,53000,Petrol,Manual,First,14.0,1061,64,5,NaN,2.75,12,Maruti,WagonR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6588,Maruti Wagon R LXI,Kolkata,2014,54841,Petrol,Manual,First,22.5,998,67.04,5,4.75 Lakh,NaN,11,Maruti,WagonR
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796,46.3,5,NaN,NaN,15,Maruti,AltoLXI
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586,104.68,5,NaN,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197,81.80,5,NaN,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998,67.1,5,NaN,NaN,14,Maruti,WagonR

In [237]:
kilometer_maruti = kilometer_maruti.rename(columns={'Power': 'Power_bhp'})
kilometer_maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine_CC,Power_bhp,Seats,Price,Car_Age,Brand,Model
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5,5,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248,74,5,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248,75,5,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5,5,7.50,9,Maruti,VitaraBrezza
403,Maruti Wagon R LXI BSIII,Pune,2013,53000,Petrol,Manual,First,14.0,1061,64,5,2.75,12,Maruti,WagonR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6588,Maruti Wagon R LXI,Kolkata,2014,54841,Petrol,Manual,First,22.5,998,67.04,5,NaN,11,Maruti,WagonR
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796,46.3,5,NaN,15,Maruti,AltoLXI
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586,104.68,5,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197,81.80,5,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998,67.1,5,NaN,14,Maruti,WagonR

In [240]:
kilometer_maruti.Price.unique()

array([ 8.63,  4.25,  3.3 ,  7.5 ,  2.75,  6.2 ,  3.51,  2.9 ,  6.25,
        3.2 ,  3.55,  3.1 ,  5.45,  2.65,  4.74,  8.5 ,  2.35,  5.  ,
        6.75,  2.41,  6.45,  8.62,  4.2 ,  5.25,  5.7 ,  5.95,  1.95,
        5.36,  3.45,  4.3 ,  2.25, 10.15,  1.75,  3.9 ,  3.87,  2.7 ,
        6.67,  2.93,  7.67,  3.04,  4.4 ,  1.1 ,  3.01,  4.06,  3.95,
        3.41,  3.  ,  5.65,  6.9 ,  2.6 ,  2.45,   nan])

In [243]:
petrol_mean_price = kilometer_maruti[kilometer_maruti['Fuel_Type']=="Petrol"]['Price'].mean()
petrol_mean_price

np.float64(3.2525)

In [244]:
diesel_mean_price = kilometer_maruti[kilometer_maruti['Fuel_Type']=="Diesel"]['Price'].mean()
diesel_mean_price

np.float64(6.043846153846155)

In [246]:
kilometer_maruti[kilometer_maruti['Fuel_Type']=="Petrol"].isna().sum()

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine_CC             0
Power_bhp             0
Seats                 0
Price                10
Car_Age               0
Brand                 0
Model                 0
dtype: int64

In [247]:
diesel_maruti_price = kilometer_maruti[kilometer_maruti['Fuel_Type']=="Diesel"]
diesel_maruti_price

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine_CC,Power_bhp,Seats,Price,Car_Age,Brand,Model
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5,5,8.63,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248,74,5,4.25,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248,75,5,3.30,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5,5,7.50,9,Maruti,VitaraBrezza
595,Maruti Swift LDI Optional,Kochi,2018,52010,Diesel,Manual,First,25.2,1248,74,5,6.20,7,Maruti,SwiftLDI
734,Maruti Swift VDI BSIV,Kolkata,2012,52241,Diesel,Manual,First,25.2,1248,74,5,2.90,13,Maruti,SwiftVDI
738,Maruti Swift LDI SP Limited Edition,Hyderabad,2016,54631,Diesel,Manual,First,25.2,1248,74,5,6.25,9,Maruti,SwiftLDI
892,Maruti Swift ZDI,Delhi,2012,52000,Diesel,Manual,First,28.4,1248,74,5,3.55,13,Maruti,SwiftZDI
1772,Maruti Swift VDI,Hyderabad,2013,53996,Diesel,Manual,First,22.9,1248,74,5,5.45,12,Maruti,SwiftVDI
1966,Maruti Swift LDI,Delhi,2015,51000,Diesel,Manual,First,22.9,1248,74,5,4.74,10,Maruti,SwiftLDI
2018,Maruti Ciaz ZDi SHVS,Pune,2016,50000,Diesel,Manual,First,28.09,1248,88.5,5,8.50,9,Maruti,CiazZDi
2360,Maruti Swift Dzire LDI,Delhi,2015,53503,Diesel,Manual,First,26.59,1248,74,5,5.00,10,Maruti,SwiftDzire
2501,Maruti Swift VDI BSIV,Hyderabad,2016,51787,Diesel,Manual,First,17.8,1248,null,5,6.45,9,Maruti,SwiftVDI
2707,Maruti Vitara Brezza VDi Option,Kochi,2018,51921,Diesel,Manual,First,24.3,1248,88.5,5,8.62,7,Maruti,VitaraBrezza
2901,Maruti Swift Dzire VDI,Delhi,2014,52000,Diesel,Manual,First,23.4,1248,74,5,5.25,11,Maruti,SwiftDzire
2979,Maruti Swift VDi BSIII W/ ABS,Jaipur,2015,50000,Diesel,Manual,First,17.8,1248,75,5,5.70,10,Maruti,SwiftVDi
3012,Maruti Swift LDI,Hyderabad,2016,52000,Diesel,Manual,First,28.4,1248,74,5,5.95,9,Maruti,SwiftLDI
3040,Maruti Swift VDI,Kochi,2015,53500,Diesel,Manual,First,28.4,1248,74,5,5.36,10,Maruti,SwiftVDI
3202,Maruti Swift VDI,Delhi,2014,50000,Diesel,Manual,First,22.9,1248,74,5,4.30,11,Maruti,SwiftVDI
3326,Maruti Ciaz ZDi Plus SHVS,Ahmedabad,2015,52324,Diesel,Manual,First,28.09,1248,88.5,5,6.25,10,Maruti,CiazZDi
3425,Maruti Vitara Brezza ZDi Plus,Coimbatore,2018,52380,Diesel,Manual,First,24.3,1248,88.5,5,10.15,7,Maruti,VitaraBrezza
4147,Maruti Dzire VDI,Kochi,2017,54758,Diesel,Manual,First,28.4,1248,73.75,5,6.67,8,Maruti,DzireVDI
4374,Maruti Ciaz ZDi Plus SHVS,Coimbatore,2016,54268,Diesel,Manual,First,28.09,1248,88.5,5,7.67,9,Maruti,CiazZDi
4385,Maruti Baleno Zeta 1.3,Delhi,2015,54000,Diesel,Manual,First,27.39,1248,74,5,5.95,10,Maruti,BalenoZeta
5640,Maruti Swift VDI,Jaipur,2016,55000,Diesel,Manual,First,22.9,1248,74,5,5.65,9,Maruti,SwiftVDI
5646,Maruti Ciaz ZDi Plus SHVS,Ahmedabad,2015,52000,Diesel,Manual,First,28.09,1248,88.5,5,6.90,10,Maruti,CiazZDi
6137,Maruti Swift Dzire Vdi BSIV,Delhi,2015,51000,Diesel,Manual,First,19.3,1248,73.9,5,NaN,10,Maruti,SwiftDzire
6459,Maruti Swift VDI Optional,Bangalore,2017,51000,Diesel,Manual,First,25.2,1248,74,5,NaN,8,Maruti,SwiftVDI

In [248]:
diesel_maruti_price.fillna(diesel_mean_price, inplace = True)

<ipython-input-248-8d47c1ad05ae>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diesel_maruti_price.fillna(diesel_mean_price, inplace = True)

In [249]:
diesel_maruti_price

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine_CC,Power_bhp,Seats,Price,Car_Age,Brand,Model
36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5,5,8.630000,7,Maruti,VitaraBrezza
51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.9,1248,74,5,4.250000,11,Maruti,SwiftLDI
52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.8,1248,75,5,3.300000,11,Maruti,SwiftLdi
119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5,5,7.500000,9,Maruti,VitaraBrezza
595,Maruti Swift LDI Optional,Kochi,2018,52010,Diesel,Manual,First,25.2,1248,74,5,6.200000,7,Maruti,SwiftLDI
734,Maruti Swift VDI BSIV,Kolkata,2012,52241,Diesel,Manual,First,25.2,1248,74,5,2.900000,13,Maruti,SwiftVDI
738,Maruti Swift LDI SP Limited Edition,Hyderabad,2016,54631,Diesel,Manual,First,25.2,1248,74,5,6.250000,9,Maruti,SwiftLDI
892,Maruti Swift ZDI,Delhi,2012,52000,Diesel,Manual,First,28.4,1248,74,5,3.550000,13,Maruti,SwiftZDI
1772,Maruti Swift VDI,Hyderabad,2013,53996,Diesel,Manual,First,22.9,1248,74,5,5.450000,12,Maruti,SwiftVDI
1966,Maruti Swift LDI,Delhi,2015,51000,Diesel,Manual,First,22.9,1248,74,5,4.740000,10,Maruti,SwiftLDI
2018,Maruti Ciaz ZDi SHVS,Pune,2016,50000,Diesel,Manual,First,28.09,1248,88.5,5,8.500000,9,Maruti,CiazZDi
2360,Maruti Swift Dzire LDI,Delhi,2015,53503,Diesel,Manual,First,26.59,1248,74,5,5.000000,10,Maruti,SwiftDzire
2501,Maruti Swift VDI BSIV,Hyderabad,2016,51787,Diesel,Manual,First,17.8,1248,null,5,6.450000,9,Maruti,SwiftVDI
2707,Maruti Vitara Brezza VDi Option,Kochi,2018,51921,Diesel,Manual,First,24.3,1248,88.5,5,8.620000,7,Maruti,VitaraBrezza
2901,Maruti Swift Dzire VDI,Delhi,2014,52000,Diesel,Manual,First,23.4,1248,74,5,5.250000,11,Maruti,SwiftDzire
2979,Maruti Swift VDi BSIII W/ ABS,Jaipur,2015,50000,Diesel,Manual,First,17.8,1248,75,5,5.700000,10,Maruti,SwiftVDi
3012,Maruti Swift LDI,Hyderabad,2016,52000,Diesel,Manual,First,28.4,1248,74,5,5.950000,9,Maruti,SwiftLDI
3040,Maruti Swift VDI,Kochi,2015,53500,Diesel,Manual,First,28.4,1248,74,5,5.360000,10,Maruti,SwiftVDI
3202,Maruti Swift VDI,Delhi,2014,50000,Diesel,Manual,First,22.9,1248,74,5,4.300000,11,Maruti,SwiftVDI
3326,Maruti Ciaz ZDi Plus SHVS,Ahmedabad,2015,52324,Diesel,Manual,First,28.09,1248,88.5,5,6.250000,10,Maruti,CiazZDi
3425,Maruti Vitara Brezza ZDi Plus,Coimbatore,2018,52380,Diesel,Manual,First,24.3,1248,88.5,5,10.150000,7,Maruti,VitaraBrezza
4147,Maruti Dzire VDI,Kochi,2017,54758,Diesel,Manual,First,28.4,1248,73.75,5,6.670000,8,Maruti,DzireVDI
4374,Maruti Ciaz ZDi Plus SHVS,Coimbatore,2016,54268,Diesel,Manual,First,28.09,1248,88.5,5,7.670000,9,Maruti,CiazZDi
4385,Maruti Baleno Zeta 1.3,Delhi,2015,54000,Diesel,Manual,First,27.39,1248,74,5,5.950000,10,Maruti,BalenoZeta
5640,Maruti Swift VDI,Jaipur,2016,55000,Diesel,Manual,First,22.9,1248,74,5,5.650000,9,Maruti,SwiftVDI
5646,Maruti Ciaz ZDi Plus SHVS,Ahmedabad,2015,52000,Diesel,Manual,First,28.09,1248,88.5,5,6.900000,10,Maruti,CiazZDi
6137,Maruti Swift Dzire Vdi BSIV,Delhi,2015,51000,Diesel,Manual,First,19.3,1248,73.9,5,6.043846,10,Maruti,SwiftDzire
6459,Maruti Swift VDI Optional,Bangalore,2017,51000,Diesel,Manual,First,25.2,1248,74,5,6.043846,8,Maruti,SwiftVDI

In [251]:
petrol_maruti_price = kilometer_maruti[kilometer_maruti['Fuel_Type']=="Petrol"]
petrol_maruti_price

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine_CC,Power_bhp,Seats,Price,Car_Age,Brand,Model
403,Maruti Wagon R LXI BSIII,Pune,2013,53000,Petrol,Manual,First,14.0,1061,64,5,2.75,12,Maruti,WagonR
716,Maruti Alto 800 LXI,Kochi,2017,54250,Petrol,Manual,First,22.74,796,47.3,5,3.51,8,Maruti,Alto800
889,Maruti Wagon R LXI,Ahmedabad,2015,51530,Petrol,Manual,First,18.9,998,67.1,5,3.20,10,Maruti,WagonR
979,Maruti Wagon R VXI BS IV,Pune,2014,51000,Petrol,Manual,First,20.51,998,67.04,5,3.10,11,Maruti,WagonR
1160,Maruti Baleno Delta 1.2,Delhi,2016,50003,Petrol,Manual,First,21.4,1197,83.1,5,5.45,9,Maruti,BalenoDelta
1478,Maruti Alto K10 LXI,Delhi,2015,51000,Petrol,Manual,First,20.92,998,67.1,5,2.65,10,Maruti,AltoK10
2137,Maruti Wagon R LXI,Hyderabad,2012,52618,Petrol,Manual,First,18.9,998,67.1,5,3.20,13,Maruti,WagonR
2245,Maruti Wagon R VXI 1.2,Mumbai,2015,55000,Petrol,Manual,First,21.5,1197,81.80,5,3.10,10,Maruti,WagonR
2252,Maruti Omni 8 Seater BSIV,Hyderabad,2015,52950,Petrol,Manual,First,14.0,796,35,5,2.35,10,Maruti,Omni8
2391,Maruti Ciaz VXi Plus,Kochi,2016,51950,Petrol,Manual,First,20.73,1373,91.1,5,6.75,9,Maruti,CiazVXi
2399,Maruti Swift VXI BSIII,Ahmedabad,2008,52000,Petrol,Manual,First,16.1,1298,88.2,5,2.41,17,Maruti,SwiftVXI
2805,Maruti Swift VXI,Delhi,2014,55000,Petrol,Manual,First,18.6,1197,85.8,5,4.20,11,Maruti,SwiftVXI
3035,Maruti Swift Lxi BSIII,Mumbai,2009,53001,Petrol,Manual,First,16.1,1298,88.2,5,1.95,16,Maruti,SwiftLxi
3181,Maruti Wagon R VXI,Chennai,2014,52000,Petrol,Manual,First,22.5,998,67.04,5,3.45,11,Maruti,WagonR
3223,Maruti A-Star Vxi,Hyderabad,2008,51366,Petrol,Manual,First,19.0,998,66.1,5,2.25,17,Maruti,A-StarVxi
3605,Maruti Alto 800 LXI Airbag,Jaipur,2015,50000,Petrol,Manual,First,22.74,796,47.3,5,2.75,10,Maruti,Alto800
3623,Maruti Alto LXi,Hyderabad,2007,52195,Petrol,Manual,First,19.7,796,46.3,5,1.75,18,Maruti,AltoLXi
3698,Maruti SX4 ZXI MT BSIV,Mumbai,2012,51800,Petrol,Manual,First,15.5,1586,103.3,5,3.90,13,Maruti,SX4ZXI
3828,Maruti Wagon R LXI,Kochi,2015,50230,Petrol,Manual,First,18.9,998,67.1,5,3.87,10,Maruti,WagonR
4010,Maruti A-Star Vxi,Hyderabad,2011,53766,Petrol,Manual,First,19.0,998,66.1,5,2.70,14,Maruti,A-StarVxi
4026,Maruti Alto K10 VXI,Jaipur,2016,51264,Petrol,Manual,First,24.07,998,67.1,5,3.20,9,Maruti,AltoK10
4109,Maruti Ciaz VXi Plus,Mumbai,2015,51579,Petrol,Manual,First,20.73,1373,91.1,5,5.95,10,Maruti,CiazVXi
4221,Maruti Alto K10 LXI,Kochi,2014,51349,Petrol,Manual,First,24.07,998,67.1,5,2.93,11,Maruti,AltoK10
4413,Maruti Alto 800 LXI,Kochi,2016,51639,Petrol,Manual,First,22.74,796,47.3,5,3.04,9,Maruti,Alto800
4664,Maruti Swift ZXI,Hyderabad,2011,53080,Petrol,Manual,First,18.6,1197,85.8,5,4.40,14,Maruti,SwiftZXI
4781,Maruti Alto LXI,Hyderabad,2007,52195,Petrol,Manual,First,19.7,796,46.3,5,1.75,18,Maruti,AltoLXI
4840,Maruti Alto LXi BSII,Mumbai,2008,54000,Petrol,Manual,First,19.7,796,46.3,5,1.10,17,Maruti,AltoLXi
4880,Maruti Wagon R LXI,Kochi,2014,52431,Petrol,Manual,First,22.5,998,67.04,5,3.01,11,Maruti,WagonR
5061,Maruti Swift Dzire VXi,Pune,2013,55000,Petrol,Manual,First,17.5,1298,85.8,5,4.25,12,Maruti,SwiftDzire
5106,Maruti Ritz VXi,Coimbatore,2011,50318,Petrol,Manual,First,18.5,1197,85.80,5,4.06,14,Maruti,RitzVXi
5165,Maruti Swift ZXI,Pune,2013,52000,Petrol,Manual,First,18.6,1197,85.8,5,3.95,12,Maruti,SwiftZXI
5192,Maruti Swift LXI BSIV,Coimbatore,2008,50121,Petrol,Manual,First,20.4,1197,83.11,5,3.41,17,Maruti,SwiftLXI
5327,Maruti Swift Dzire VXi,Hyderabad,2012,50000,Petrol,Manual,First,17.5,1298,85.8,5,3.00,13,Maruti,SwiftDzire
5773,Maruti SX4 Vxi BSIV,Delhi,2011,52000,Petrol,Manual,First,15.5,1586,103.3,5,2.60,14,Maruti,SX4Vxi
5824,Maruti Wagon R LXI BSII,Delhi,2012,52000,Petrol,Manual,First,18.9,998,67.1,5,2.45,13,Maruti,WagonR
5888,Maruti Alto K10 2010-2014 VXI,Chennai,2014,52000,Petrol,Manual,First,20.92,998,67.1,5,2.70,11,Maruti,AltoK10
6054,Maruti Swift Dzire VXI,Chennai,2015,51000,Petrol,Manual,First,19.1,1197,85.8,5,NaN,10,Maruti,SwiftDzire
6117,Maruti Zen Estilo LXI BS IV,Pune,2011,51599,Petrol,Manual,First,19.0,998,67.1,5,NaN,14,Maruti,ZenEstilo
6324,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,53313,Petrol,Manual,First,20.92,998,67.1,5,NaN,12,Maruti,AltoK10
6375,Maruti Wagon R VXI BS IV,Kolkata,2014,54000,Petrol,Manual,First,20.51,998,67.04,5,NaN,11,Maruti,WagonR
6394,Maruti Eeco 5 Seater AC,Delhi,2014,51200,Petrol,Manual,First,15.1,1196,73,5,NaN,11,Maruti,Eeco5
6588,Maruti Wagon R LXI,Kolkata,2014,54841,Petrol,Manual,First,22.5,998,67.04,5,NaN,11,Maruti,WagonR
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796,46.3,5,NaN,15,Maruti,AltoLXI
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586,104.68,5,NaN,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197,81.80,5,NaN,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998,67.1,5,NaN,14,Maruti,WagonR

In [252]:
petrol_maruti_price.fillna(petrol_mean_price, inplace = True)

<ipython-input-252-e528aeb575ae>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  petrol_maruti_price.fillna(petrol_mean_price, inplace = True)

In [253]:
petrol_maruti_price

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine_CC,Power_bhp,Seats,Price,Car_Age,Brand,Model
403,Maruti Wagon R LXI BSIII,Pune,2013,53000,Petrol,Manual,First,14.0,1061,64,5,2.7500,12,Maruti,WagonR
716,Maruti Alto 800 LXI,Kochi,2017,54250,Petrol,Manual,First,22.74,796,47.3,5,3.5100,8,Maruti,Alto800
889,Maruti Wagon R LXI,Ahmedabad,2015,51530,Petrol,Manual,First,18.9,998,67.1,5,3.2000,10,Maruti,WagonR
979,Maruti Wagon R VXI BS IV,Pune,2014,51000,Petrol,Manual,First,20.51,998,67.04,5,3.1000,11,Maruti,WagonR
1160,Maruti Baleno Delta 1.2,Delhi,2016,50003,Petrol,Manual,First,21.4,1197,83.1,5,5.4500,9,Maruti,BalenoDelta
1478,Maruti Alto K10 LXI,Delhi,2015,51000,Petrol,Manual,First,20.92,998,67.1,5,2.6500,10,Maruti,AltoK10
2137,Maruti Wagon R LXI,Hyderabad,2012,52618,Petrol,Manual,First,18.9,998,67.1,5,3.2000,13,Maruti,WagonR
2245,Maruti Wagon R VXI 1.2,Mumbai,2015,55000,Petrol,Manual,First,21.5,1197,81.80,5,3.1000,10,Maruti,WagonR
2252,Maruti Omni 8 Seater BSIV,Hyderabad,2015,52950,Petrol,Manual,First,14.0,796,35,5,2.3500,10,Maruti,Omni8
2391,Maruti Ciaz VXi Plus,Kochi,2016,51950,Petrol,Manual,First,20.73,1373,91.1,5,6.7500,9,Maruti,CiazVXi
2399,Maruti Swift VXI BSIII,Ahmedabad,2008,52000,Petrol,Manual,First,16.1,1298,88.2,5,2.4100,17,Maruti,SwiftVXI
2805,Maruti Swift VXI,Delhi,2014,55000,Petrol,Manual,First,18.6,1197,85.8,5,4.2000,11,Maruti,SwiftVXI
3035,Maruti Swift Lxi BSIII,Mumbai,2009,53001,Petrol,Manual,First,16.1,1298,88.2,5,1.9500,16,Maruti,SwiftLxi
3181,Maruti Wagon R VXI,Chennai,2014,52000,Petrol,Manual,First,22.5,998,67.04,5,3.4500,11,Maruti,WagonR
3223,Maruti A-Star Vxi,Hyderabad,2008,51366,Petrol,Manual,First,19.0,998,66.1,5,2.2500,17,Maruti,A-StarVxi
3605,Maruti Alto 800 LXI Airbag,Jaipur,2015,50000,Petrol,Manual,First,22.74,796,47.3,5,2.7500,10,Maruti,Alto800
3623,Maruti Alto LXi,Hyderabad,2007,52195,Petrol,Manual,First,19.7,796,46.3,5,1.7500,18,Maruti,AltoLXi
3698,Maruti SX4 ZXI MT BSIV,Mumbai,2012,51800,Petrol,Manual,First,15.5,1586,103.3,5,3.9000,13,Maruti,SX4ZXI
3828,Maruti Wagon R LXI,Kochi,2015,50230,Petrol,Manual,First,18.9,998,67.1,5,3.8700,10,Maruti,WagonR
4010,Maruti A-Star Vxi,Hyderabad,2011,53766,Petrol,Manual,First,19.0,998,66.1,5,2.7000,14,Maruti,A-StarVxi
4026,Maruti Alto K10 VXI,Jaipur,2016,51264,Petrol,Manual,First,24.07,998,67.1,5,3.2000,9,Maruti,AltoK10
4109,Maruti Ciaz VXi Plus,Mumbai,2015,51579,Petrol,Manual,First,20.73,1373,91.1,5,5.9500,10,Maruti,CiazVXi
4221,Maruti Alto K10 LXI,Kochi,2014,51349,Petrol,Manual,First,24.07,998,67.1,5,2.9300,11,Maruti,AltoK10
4413,Maruti Alto 800 LXI,Kochi,2016,51639,Petrol,Manual,First,22.74,796,47.3,5,3.0400,9,Maruti,Alto800
4664,Maruti Swift ZXI,Hyderabad,2011,53080,Petrol,Manual,First,18.6,1197,85.8,5,4.4000,14,Maruti,SwiftZXI
4781,Maruti Alto LXI,Hyderabad,2007,52195,Petrol,Manual,First,19.7,796,46.3,5,1.7500,18,Maruti,AltoLXI
4840,Maruti Alto LXi BSII,Mumbai,2008,54000,Petrol,Manual,First,19.7,796,46.3,5,1.1000,17,Maruti,AltoLXi
4880,Maruti Wagon R LXI,Kochi,2014,52431,Petrol,Manual,First,22.5,998,67.04,5,3.0100,11,Maruti,WagonR
5061,Maruti Swift Dzire VXi,Pune,2013,55000,Petrol,Manual,First,17.5,1298,85.8,5,4.2500,12,Maruti,SwiftDzire
5106,Maruti Ritz VXi,Coimbatore,2011,50318,Petrol,Manual,First,18.5,1197,85.80,5,4.0600,14,Maruti,RitzVXi
5165,Maruti Swift ZXI,Pune,2013,52000,Petrol,Manual,First,18.6,1197,85.8,5,3.9500,12,Maruti,SwiftZXI
5192,Maruti Swift LXI BSIV,Coimbatore,2008,50121,Petrol,Manual,First,20.4,1197,83.11,5,3.4100,17,Maruti,SwiftLXI
5327,Maruti Swift Dzire VXi,Hyderabad,2012,50000,Petrol,Manual,First,17.5,1298,85.8,5,3.0000,13,Maruti,SwiftDzire
5773,Maruti SX4 Vxi BSIV,Delhi,2011,52000,Petrol,Manual,First,15.5,1586,103.3,5,2.6000,14,Maruti,SX4Vxi
5824,Maruti Wagon R LXI BSII,Delhi,2012,52000,Petrol,Manual,First,18.9,998,67.1,5,2.4500,13,Maruti,WagonR
5888,Maruti Alto K10 2010-2014 VXI,Chennai,2014,52000,Petrol,Manual,First,20.92,998,67.1,5,2.7000,11,Maruti,AltoK10
6054,Maruti Swift Dzire VXI,Chennai,2015,51000,Petrol,Manual,First,19.1,1197,85.8,5,3.2525,10,Maruti,SwiftDzire
6117,Maruti Zen Estilo LXI BS IV,Pune,2011,51599,Petrol,Manual,First,19.0,998,67.1,5,3.2525,14,Maruti,ZenEstilo
6324,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,53313,Petrol,Manual,First,20.92,998,67.1,5,3.2525,12,Maruti,AltoK10
6375,Maruti Wagon R VXI BS IV,Kolkata,2014,54000,Petrol,Manual,First,20.51,998,67.04,5,3.2525,11,Maruti,WagonR
6394,Maruti Eeco 5 Seater AC,Delhi,2014,51200,Petrol,Manual,First,15.1,1196,73,5,3.2525,11,Maruti,Eeco5
6588,Maruti Wagon R LXI,Kolkata,2014,54841,Petrol,Manual,First,22.5,998,67.04,5,3.2525,11,Maruti,WagonR
6823,Maruti Alto LXI,Hyderabad,2010,54486,Petrol,Manual,First,19.7,796,46.3,5,3.2525,15,Maruti,AltoLXI
6968,Maruti SX4 Zxi BSIII,Mumbai,2011,54000,Petrol,Manual,First,15.0,1586,104.68,5,3.2525,14,Maruti,SX4Zxi
7085,Maruti Swift VXI BSIV,Coimbatore,2015,53556,Petrol,Manual,First,20.4,1197,81.80,5,3.2525,10,Maruti,SwiftVXI
7101,Maruti Wagon R VXI BSIII,Mumbai,2011,50215,Petrol,Manual,First,18.9,998,67.1,5,3.2525,14,Maruti,WagonR

In [254]:
diesel_maruti_price.shape

(28, 15)

In [255]:
petrol_maruti_price.shape

(46, 15)

In [256]:
final_maruti_petrol = petrol_maruti_price[['Kilometers_Driven','Car_Age','Mileage','Engine_CC','Power_bhp','Price']]

In [257]:
final_maruti_petrol

      Kilometers_Driven  Car_Age Mileage Engine_CC Power_bhp   Price
403               53000       12    14.0      1061        64  2.7500
716               54250        8   22.74       796      47.3  3.5100
889               51530       10    18.9       998      67.1  3.2000
979               51000       11   20.51       998     67.04  3.1000
1160              50003        9    21.4      1197      83.1  5.4500
1478              51000       10   20.92       998      67.1  2.6500
2137              52618       13    18.9       998      67.1  3.2000
2245              55000       10    21.5      1197     81.80  3.1000
2252              52950       10    14.0       796        35  2.3500
2391              51950        9   20.73      1373      91.1  6.7500
2399              52000       17    16.1      1298      88.2  2.4100
2805              55000       11    18.6      1197      85.8  4.2000
3035              53001       16    16.1      1298      88.2  1.9500
3181              52000       11    22.5       998     67.04  3.4500
3223              51366       17    19.0       998      66.1  2.2500
3605              50000       10   22.74       796      47.3  2.7500
3623              52195       18    19.7       796      46.3  1.7500
3698              51800       13    15.5      1586     103.3  3.9000
3828              50230       10    18.9       998      67.1  3.8700
4010              53766       14    19.0       998      66.1  2.7000
4026              51264        9   24.07       998      67.1  3.2000
4109              51579       10   20.73      1373      91.1  5.9500
4221              51349       11   24.07       998      67.1  2.9300
4413              51639        9   22.74       796      47.3  3.0400
4664              53080       14    18.6      1197      85.8  4.4000
4781              52195       18    19.7       796      46.3  1.7500
4840              54000       17    19.7       796      46.3  1.1000
4880              52431       11    22.5       998     67.04  3.0100
5061              55000       12    17.5      1298      85.8  4.2500
5106              50318       14    18.5      1197     85.80  4.0600
5165              52000       12    18.6      1197      85.8  3.9500
5192              50121       17    20.4      1197     83.11  3.4100
5327              50000       13    17.5      1298      85.8  3.0000
5773              52000       14    15.5      1586     103.3  2.6000
5824              52000       13    18.9       998      67.1  2.4500
5888              52000       11   20.92       998      67.1  2.7000
6054              51000       10    19.1      1197      85.8  3.2525
6117              51599       14    19.0       998      67.1  3.2525
6324              53313       12   20.92       998      67.1  3.2525
6375              54000       11   20.51       998     67.04  3.2525
6394              51200       11    15.1      1196        73  3.2525
6588              54841       11    22.5       998     67.04  3.2525
6823              54486       15    19.7       796      46.3  3.2525
6968              54000       14    15.0      1586    104.68  3.2525
7085              53556       10    20.4      1197     81.80  3.2525
7101              50215       14    18.9       998      67.1  3.2525

In [258]:
final_maruti_petrol.dtypes

Kilometers_Driven      int64
Car_Age                int64
Mileage               object
Engine_CC             object
Power_bhp             object
Price                float64
dtype: object

In [259]:
final_maruti_petrol.Mileage = final_maruti_petrol.Mileage.astype(float)

<ipython-input-259-9001d97c9380>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_maruti_petrol.Mileage = final_maruti_petrol.Mileage.astype(float)

In [260]:
final_maruti_petrol.Power_bhp = final_maruti_petrol.Power_bhp.astype(float)

<ipython-input-260-a28a36e98e7d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_maruti_petrol.Power_bhp = final_maruti_petrol.Power_bhp.astype(float)

In [261]:
final_maruti_petrol.Engine_CC = final_maruti_petrol.Engine_CC.astype(float)

<ipython-input-261-a8a5898649e0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_maruti_petrol.Engine_CC = final_maruti_petrol.Engine_CC.astype(float)

In [262]:
final_maruti_petrol.dtypes

Kilometers_Driven      int64
Car_Age                int64
Mileage              float64
Engine_CC            float64
Power_bhp            float64
Price                float64
dtype: object

In [272]:
# prompt: i need to predict the price from final_maruti_petrol

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Prepare data for modeling
X = final_maruti_petrol[['Kilometers_Driven', 'Car_Age', 'Mileage', 'Engine_CC', 'Power_bhp']]
y = final_maruti_petrol['Price']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Example prediction for a new car
new_car_data = pd.DataFrame([[51950, 9, 20.73, 1373, 90]], columns=['Kilometers_Driven', 'Car_Age', 'Mileage', 'Engine_CC', 'Power_bhp'])
predicted_price = model.predict(new_car_data)
print(f"Predicted price for the new car: {predicted_price[0]:.2f} lakhs")

Mean Squared Error: 0.5280344197441977
R-squared: 0.5826404817032946
Predicted price for the new car: 4.49 lakhs

In [269]:
final_maruti_petrol[(final_maruti_petrol['Kilometers_Driven'] >= 51500) & (final_maruti_petrol['Kilometers_Driven'] <= 52000)]

      Kilometers_Driven  Car_Age  Mileage  Engine_CC  Power_bhp   Price
889               51530       10    18.90      998.0      67.10  3.2000
2391              51950        9    20.73     1373.0      91.10  6.7500
2399              52000       17    16.10     1298.0      88.20  2.4100
3181              52000       11    22.50      998.0      67.04  3.4500
3698              51800       13    15.50     1586.0     103.30  3.9000
4109              51579       10    20.73     1373.0      91.10  5.9500
4413              51639        9    22.74      796.0      47.30  3.0400
5165              52000       12    18.60     1197.0      85.80  3.9500
5773              52000       14    15.50     1586.0     103.30  2.6000
5824              52000       13    18.90      998.0      67.10  2.4500
5888              52000       11    20.92      998.0      67.10  2.7000
6117              51599       14    19.00      998.0      67.10  3.2525

In [273]:
ProfileReport(final_maruti_petrol,title = "Final Maruti Report").to_file('final_maruti_report.html')

/usr/local/lib/python3.11/dist-packages/ydata_profiling/utils/dataframe.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"index": "df_index"}, inplace=True)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 6/6 [00:00<00:00, 105.04it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [277]:
final_maruti_petrol.to_csv("final_maruti_petrol.csv")

In [278]:
final_maruti_petrol

      Kilometers_Driven  Car_Age  Mileage  Engine_CC  Power_bhp   Price
403               53000       12    14.00     1061.0      64.00  2.7500
716               54250        8    22.74      796.0      47.30  3.5100
889               51530       10    18.90      998.0      67.10  3.2000
979               51000       11    20.51      998.0      67.04  3.1000
1160              50003        9    21.40     1197.0      83.10  5.4500
1478              51000       10    20.92      998.0      67.10  2.6500
2137              52618       13    18.90      998.0      67.10  3.2000
2245              55000       10    21.50     1197.0      81.80  3.1000
2252              52950       10    14.00      796.0      35.00  2.3500
2391              51950        9    20.73     1373.0      91.10  6.7500
2399              52000       17    16.10     1298.0      88.20  2.4100
2805              55000       11    18.60     1197.0      85.80  4.2000
3035              53001       16    16.10     1298.0      88.20  1.9500
3181              52000       11    22.50      998.0      67.04  3.4500
3223              51366       17    19.00      998.0      66.10  2.2500
3605              50000       10    22.74      796.0      47.30  2.7500
3623              52195       18    19.70      796.0      46.30  1.7500
3698              51800       13    15.50     1586.0     103.30  3.9000
3828              50230       10    18.90      998.0      67.10  3.8700
4010              53766       14    19.00      998.0      66.10  2.7000
4026              51264        9    24.07      998.0      67.10  3.2000
4109              51579       10    20.73     1373.0      91.10  5.9500
4221              51349       11    24.07      998.0      67.10  2.9300
4413              51639        9    22.74      796.0      47.30  3.0400
4664              53080       14    18.60     1197.0      85.80  4.4000
4781              52195       18    19.70      796.0      46.30  1.7500
4840              54000       17    19.70      796.0      46.30  1.1000
4880              52431       11    22.50      998.0      67.04  3.0100
5061              55000       12    17.50     1298.0      85.80  4.2500
5106              50318       14    18.50     1197.0      85.80  4.0600
5165              52000       12    18.60     1197.0      85.80  3.9500
5192              50121       17    20.40     1197.0      83.11  3.4100
5327              50000       13    17.50     1298.0      85.80  3.0000
5773              52000       14    15.50     1586.0     103.30  2.6000
5824              52000       13    18.90      998.0      67.10  2.4500
5888              52000       11    20.92      998.0      67.10  2.7000
6054              51000       10    19.10     1197.0      85.80  3.2525
6117              51599       14    19.00      998.0      67.10  3.2525
6324              53313       12    20.92      998.0      67.10  3.2525
6375              54000       11    20.51      998.0      67.04  3.2525
6394              51200       11    15.10     1196.0      73.00  3.2525
6588              54841       11    22.50      998.0      67.04  3.2525
6823              54486       15    19.70      796.0      46.30  3.2525
6968              54000       14    15.00     1586.0     104.68  3.2525
7085              53556       10    20.40     1197.0      81.80  3.2525
7101              50215       14    18.90      998.0      67.10  3.2525

Creating function for all the process done

In [279]:
final_maruti_petrol.shape

(46, 6)