<a href="https://colab.research.google.com/github/kabirNahata/Learning-journey/blob/main/EDA_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Step 1: Import Python Libraries**

Pandas and Numpy have been used for Data Manipulation and numerical Calculations

Matplotlib and Seaborn have been used for Data visualizations.

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport

**Step 2: Reading Dataset**

In [9]:
data = pd.read_csv("used_cars_data.csv")

In [10]:
data_report = ProfileReport(data, title="Used Cars Data Report")
report = data_report.to_file("used_cars_data_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]
 14%|█▍        | 2/14 [00:00<00:01,  9.94it/s]
 43%|████▎     | 6/14 [00:00<00:00, 18.77it/s]
 64%|██████▍   | 9/14 [00:00<00:00, 17.93it/s]
 79%|███████▊  | 11/14 [00:00<00:00, 16.97it/s]
100%|██████████| 14/14 [00:01<00:00, 11.88it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Analyzing the Data

shape – shape will display the number of observations(rows) and features(columns) in the dataset

In [11]:
data.shape

(7253, 14)

head() will display the top 5 observations of the dataset

In [12]:
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

tail() will display the last 5 observations of the dataset

In [13]:
data.tail()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

info() helps to understand the data type and information about data, including the number of records in each column, data having null or not null, Data type, the memory usage of the dataset

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   object
 2   Location           7253 non-null   object
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   object
 6   Transmission       7253 non-null   object
 7   Owner_Type         7253 non-null   object
 8   Mileage            7251 non-null   object
 9   Engine             7207 non-null   object
 10  Power              7207 non-null   object
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   object
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 793.4+ KB

nunique() based on several unique values in each column and the data description, we can identify the continuous and categorical columns in the data. Duplicated data can be handled or removed based on further analysis

In [15]:
data.nunique()

S.No.                7253
Name                 2041
Location               11
Year                   23
Kilometers_Driven    3660
Fuel_Type               5
Transmission            2
Owner_Type              4
Mileage               450
Engine                150
Power                 386
Seats                   9
New_Price             625
Price                1373
dtype: int64

isnull() is widely been in all pre-processing steps to identify null values in the data

In our example, data.isnull().sum() is used to get the number of missing records in each column

In [16]:
data.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

The below code helps to calculate the percentage of missing values in each column

In [17]:
data.isnull().sum()/(len((data)))*100

S.No.                 0.000000
Name                  0.000000
Location              0.000000
Year                  0.000000
Kilometers_Driven     0.000000
Fuel_Type             0.000000
Transmission          0.000000
Owner_Type            0.000000
Mileage               0.027575
Engine                0.634220
Power                 0.634220
Seats                 0.730732
New_Price            86.129877
Price                17.013650
dtype: float64

The percentage of missing values for the columns New_Price and Price is ~86% and ~17%, respectively.

**Step 3: Data Reduction**

Some columns or variables can be dropped if they do not add value to our analysis.

In our dataset, the column S.No have only ID values, assuming they don’t have any predictive power to predict the dependent variable.

In [18]:
# Remove S.No. column from data
data = data.drop(['S.No.'], axis = 1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   object
 1   Location           7253 non-null   object
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   object
 5   Transmission       7253 non-null   object
 6   Owner_Type         7253 non-null   object
 7   Mileage            7251 non-null   object
 8   Engine             7207 non-null   object
 9   Power              7207 non-null   object
 10  Seats              7200 non-null   float64
 11  New_Price          1006 non-null   object
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(2), object(9)
memory usage: 736.8+ KB

We start our Feature Engineering as we need to add some columns required for analysis.

**Step 4: Feature Engineering**

Feature engineering refers to the process of using domain knowledge to select and transform the most relevant variables from raw data when creating a predictive model using machine learning or statistical modeling. The main goal of Feature engineering is to create meaningful data from raw data.

**Step 5: Creating Features**

It would be difficult to find the car’s age if it is in year format as the Age of the car is a contributing factor to Car Price.

Introducing a new column, “Car_Age” to know the age of the car

In [19]:
from datetime import date
date.today().year
data['Car_Age']=date.today().year-data['Year']
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,15
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,10
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,14
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,13
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,12

Since car names will not be great predictors of the price in our current data. But we can process this column to extract important information using brand and Model names. Let’s split the name and introduce new variables “Brand” and “Model”

In [20]:
data['Brand'] = data.Name.str.split().str.get(0)

In [21]:
data['Model'] = data.Name.str.split().str.get(1) + data.Name.str.split().str.get(2)

In [22]:
data[['Name','Brand','Model']]

,Name,Brand,Model
0,Maruti Wagon R LXI CNG,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Hyundai,Creta1.6
2,Honda Jazz V,Honda,JazzV
3,Maruti Ertiga VDI,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Audi,A4New
...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Volkswagen,VentoDiesel
7249,Volkswagen Polo GT TSI,Volkswagen,PoloGT
7250,Nissan Micra Diesel XV,Nissan,MicraDiesel
7251,Volkswagen Polo GT TSI,Volkswagen,PoloGT
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Mercedes-Benz,E-Class2009-2013

**Step 6: Data Cleaning/Wrangling**

Some names of the variables are not relevant and not easy to understand. Some data may have data entry errors, and some variables may need data type conversion. We need to fix this issue in the data.

In the example, The brand name ‘Isuzu’ ‘ISUZU’ and ‘Mini’ and ‘Land’ looks incorrect. This needs to be corrected

In [23]:
print(data.Brand.unique())
print(data.Brand.nunique())

['Maruti' 'Hyundai' 'Honda' 'Audi' 'Nissan' 'Toyota' 'Volkswagen' 'Tata'
 'Land' 'Mitsubishi' 'Renault' 'Mercedes-Benz' 'BMW' 'Mahindra' 'Ford'
 'Porsche' 'Datsun' 'Jaguar' 'Volvo' 'Chevrolet' 'Skoda' 'Mini' 'Fiat'
 'Jeep' 'Smart' 'Ambassador' 'Isuzu' 'ISUZU' 'Force' 'Bentley'
 'Lamborghini' 'Hindustan' 'OpelCorsa']
33

There are brand names that are not making sense, to fix them

In [24]:
searchfor = ['Isuzu' ,'ISUZU','Mini','Land']
data[data.Brand.str.contains('|'.join(searchfor))].head(5)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,27.00,11,Land,RoverRange
14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.0 kmpl,2179 CC,115 bhp,5.0,NaN,17.50,13,Land,RoverFreelander
176,Mini Countryman Cooper D,Jaipur,2017,8525,Diesel,Automatic,Second,16.6 kmpl,1998 CC,112 bhp,5.0,NaN,23.00,8,Mini,CountrymanCooper
191,Land Rover Range Rover 2.2L Dynamic,Coimbatore,2018,36091,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,55.76,7,Land,RoverRange
228,Mini Cooper Convertible S,Kochi,2017,26327,Petrol,Automatic,First,16.82 kmpl,1998 CC,189.08 bhp,4.0,44.28 Lakh,35.67,8,Mini,CooperConvertible

In [25]:
data["Brand"].replace({"ISUZU": "Isuzu", "Mini": "Mini Cooper","Land":"Land Rover"}, inplace=True)

looking at the first row

In [26]:
data.iloc[0]

Name                 Maruti Wagon R LXI CNG
Location                             Mumbai
Year                                   2010
Kilometers_Driven                     72000
Fuel_Type                               CNG
Transmission                         Manual
Owner_Type                            First
Mileage                          26.6 km/kg
Engine                               998 CC
Power                             58.16 bhp
Seats                                   5.0
New_Price                               NaN
Price                                  1.75
Car_Age                                  15
Brand                                Maruti
Model                                WagonR
Name: 0, dtype: object

value_count() counts the unique value for given column

In [27]:
data.Brand.value_counts()

Brand
Maruti           1444
Hyundai          1340
Honda             743
Toyota            507
Mercedes-Benz     380
Volkswagen        374
Ford              351
Mahindra          331
BMW               312
Audi              285
Tata              228
Skoda             202
Renault           170
Chevrolet         151
Nissan            117
Land Rover         67
Jaguar             48
Fiat               38
Mitsubishi         36
Mini Cooper        31
Volvo              28
Porsche            19
Jeep               19
Datsun             17
Isuzu               5
Force               3
Bentley             2
Ambassador          1
Smart               1
Lamborghini         1
Hindustan           1
OpelCorsa           1
Name: count, dtype: int64

In [28]:
data.Brand.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
7248    False
7249    False
7250    False
7251    False
7252    False
Name: Brand, Length: 7253, dtype: bool

duplicated() checkes for duplicated value according row by row

In [29]:
data.Brand.duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
7248     True
7249     True
7250     True
7251     True
7252     True
Name: Brand, Length: 7253, dtype: bool

In [30]:
variable = data.Brand.value_counts()

In [31]:
type(variable)

pandas.core.series.Series

In [32]:
variable["Maruti"]+2

np.int64(1446)

In [33]:
data.describe(include = "all")

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
count,7253,7253,7253.000000,7.253000e+03,7253,7253,7253,7251,7207,7207,7200.000000,1006,6019.000000,7253.000000,7253,7252
unique,2041,11,NaN,NaN,5,2,4,450,150,386,NaN,625,NaN,NaN,32,726
top,Mahindra XUV500 W8 2WD,Mumbai,NaN,NaN,Diesel,Manual,First,17.0 kmpl,1197 CC,74 bhp,NaN,95.13 Lakh,NaN,NaN,Maruti,SwiftDzire
freq,55,949,NaN,NaN,3852,5204,5952,207,732,280,NaN,6,NaN,NaN,1444,189
mean,NaN,NaN,2013.365366,5.869906e+04,NaN,NaN,NaN,NaN,NaN,NaN,5.279722,NaN,9.479468,11.634634,NaN,NaN
std,NaN,NaN,3.254421,8.442772e+04,NaN,NaN,NaN,NaN,NaN,NaN,0.811660,NaN,11.187917,3.254421,NaN,NaN
min,NaN,NaN,1996.000000,1.710000e+02,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.440000,6.000000,NaN,NaN
25%,NaN,NaN,2011.000000,3.400000e+04,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,3.500000,9.000000,NaN,NaN
50%,NaN,NaN,2014.000000,5.341600e+04,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,5.640000,11.000000,NaN,NaN
75%,NaN,NaN,2016.000000,7.300000e+04,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,9.950000,14.000000,NaN,NaN
max,NaN,NaN,2019.000000,6.500000e+06,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,160.000000,29.000000,NaN,NaN

In [34]:
data['Year']

0       2010
1       2015
2       2011
3       2012
4       2013
        ...
7248    2011
7249    2015
7250    2012
7251    2013
7252    2014
Name: Year, Length: 7253, dtype: int64

In [35]:
data.describe()

              Year  Kilometers_Driven        Seats        Price      Car_Age
count  7253.000000       7.253000e+03  7200.000000  6019.000000  7253.000000
mean   2013.365366       5.869906e+04     5.279722     9.479468    11.634634
std       3.254421       8.442772e+04     0.811660    11.187917     3.254421
min    1996.000000       1.710000e+02     0.000000     0.440000     6.000000
25%    2011.000000       3.400000e+04     5.000000     3.500000     9.000000
50%    2014.000000       5.341600e+04     5.000000     5.640000    11.000000
75%    2016.000000       7.300000e+04     5.000000     9.950000    14.000000
max    2019.000000       6.500000e+06    10.000000   160.000000    29.000000

In [36]:
data.dtypes

Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
New_Price             object
Price                float64
Car_Age                int64
Brand                 object
Model                 object
dtype: object

In [37]:
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,10,Hyundai,Creta1.6
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,14,Honda,JazzV
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,12,Audi,A4New

# change new price value to float, remove the string
# change seat into int from float

In [38]:
import numpy as np

In [39]:
temp_data = data.copy()

In [41]:
np.isfinite(temp_data.Seats)

0       True
1       True
2       True
3       True
4       True
        ...
7248    True
7249    True
7250    True
7251    True
7252    True
Name: Seats, Length: 7253, dtype: bool

In [42]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
6.0       38
2.0       18
10.0       8
9.0        3
0.0        1
Name: count, dtype: int64

In [43]:
temp_data[temp_data.Seats==0]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
3999,Audi A4 3.2 FSI Tiptronic Quattro,Hyderabad,2012,125000,Petrol,Automatic,First,10.5 kmpl,3197 CC,null bhp,0.0,NaN,18.0,13,Audi,A43.2

In [44]:
temp_data.Seats[3999] = 2

<ipython-input-44-6704346f2f04>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data.Seats[3999] = 2

In [45]:
temp_data.iloc[3999]

Name                 Audi A4 3.2 FSI Tiptronic Quattro
Location                                     Hyderabad
Year                                              2012
Kilometers_Driven                               125000
Fuel_Type                                       Petrol
Transmission                                 Automatic
Owner_Type                                       First
Mileage                                      10.5 kmpl
Engine                                         3197 CC
Power                                         null bhp
Seats                                              2.0
New_Price                                          NaN
Price                                             18.0
Car_Age                                             13
Brand                                             Audi
Model                                            A43.2
Name: 3999, dtype: object

index 3999, seats value 0 change into 2

In [46]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
6.0       38
2.0       19
10.0       8
9.0        3
Name: count, dtype: int64

Update original dataframe using temporary dataframe

In [47]:
temp_data.Seats

0       5.0
1       5.0
2       5.0
3       7.0
4       5.0
       ...
7248    5.0
7249    5.0
7250    5.0
7251    5.0
7252    5.0
Name: Seats, Length: 7253, dtype: float64

In [48]:
temp_data.Seats = data.Seats

In [49]:
temp_data.Seats

0       5.0
1       5.0
2       5.0
3       7.0
4       5.0
       ...
7248    5.0
7249    5.0
7250    5.0
7251    5.0
7252    5.0
Name: Seats, Length: 7253, dtype: float64

In [50]:
temp_data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,10,Hyundai,Creta1.6
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,14,Honda,JazzV
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,12,Audi,A4New

In [51]:
temp_data.Seats.unique()

array([ 5.,  7.,  8.,  4.,  6.,  2., nan, 10.,  9.,  0.])

In [52]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
6.0       38
2.0       18
10.0       8
9.0        3
0.0        1
Name: count, dtype: int64

In [53]:
temp_data.Seats[3999] = 2

<ipython-input-53-6704346f2f04>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data.Seats[3999] = 2

In [54]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
6.0       38
2.0       19
10.0       8
9.0        3
Name: count, dtype: int64

In [55]:
temp_data[temp_data.Seats.isna()]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
194,Honda City 1.5 GXI,Ahmedabad,2007,60006,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,2.95,18,Honda,City1.5
208,Maruti Swift 1.3 VXi,Kolkata,2010,42001,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,2.11,15,Maruti,Swift1.3
229,Ford Figo Diesel,Bangalore,2015,70436,Diesel,Manual,First,0.0 kmpl,1498 CC,99 bhp,NaN,NaN,3.60,10,Ford,FigoDiesel
733,Maruti Swift 1.3 VXi,Chennai,2006,97800,Petrol,Manual,Third,16.1 kmpl,NaN,NaN,NaN,NaN,1.75,19,Maruti,Swift1.3
749,Land Rover Range Rover 3.0 D,Mumbai,2008,55001,Diesel,Automatic,Second,0.0 kmpl,NaN,NaN,NaN,NaN,26.50,17,Land Rover,RoverRange
1294,Honda City 1.3 DX,Delhi,2009,55005,Petrol,Manual,First,12.8 kmpl,NaN,NaN,NaN,NaN,3.20,16,Honda,City1.3
1327,Maruti Swift 1.3 ZXI,Hyderabad,2015,50295,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,5.80,10,Maruti,Swift1.3
1385,Honda City 1.5 GXI,Pune,2004,115000,Petrol,Manual,Second,0.0 kmpl,NaN,NaN,NaN,NaN,1.50,21,Honda,City1.5
1460,Land Rover Range Rover Sport 2005 2012 Sport,Coimbatore,2008,69078,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,40.88,17,Land Rover,RoverRange
1917,Honda City 1.5 EXI,Jaipur,2005,88000,Petrol,Manual,Second,13.0 kmpl,1493 CC,100 bhp,NaN,NaN,1.70,20,Honda,City1.5
2074,Maruti Swift 1.3 LXI,Pune,2011,24255,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,3.15,14,Maruti,Swift1.3
2096,Hyundai Santro LP zipPlus,Coimbatore,2004,52146,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,1.93,21,Hyundai,SantroLP
2264,Toyota Etios Liva V,Pune,2012,24500,Petrol,Manual,Second,18.3 kmpl,NaN,NaN,NaN,NaN,2.95,13,Toyota,EtiosLiva
2325,Maruti Swift 1.3 VXI ABS,Pune,2015,67000,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,4.70,10,Maruti,Swift1.3
2335,Maruti Swift 1.3 VXi,Mumbai,2007,55000,Petrol,Manual,Second,16.1 kmpl,NaN,NaN,NaN,NaN,1.75,18,Maruti,Swift1.3
2369,Maruti Estilo LXI,Chennai,2008,56000,Petrol,Manual,Second,19.5 kmpl,1061 CC,null bhp,NaN,NaN,1.50,17,Maruti,EstiloLXI
2530,BMW 5 Series 520d Sedan,Kochi,2014,64158,Diesel,Automatic,First,18.48 kmpl,NaN,NaN,NaN,NaN,17.89,11,BMW,5Series
2542,Hyundai Santro GLS II - Euro II,Bangalore,2011,65000,Petrol,Manual,Second,0.0 kmpl,NaN,NaN,NaN,NaN,3.15,14,Hyundai,SantroGLS
2623,BMW 5 Series 520d Sedan,Pune,2012,95000,Diesel,Automatic,Second,18.48 kmpl,NaN,NaN,NaN,NaN,18.00,13,BMW,5Series
2668,Maruti Swift 1.3 VXi,Kolkata,2014,32986,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,4.24,11,Maruti,Swift1.3
2737,Maruti Wagon R Vx,Jaipur,2001,200000,Petrol,Manual,First,12.0 kmpl,NaN,NaN,NaN,NaN,0.70,24,Maruti,WagonR
2780,Hyundai Santro GLS II - Euro II,Pune,2009,100000,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,1.60,16,Hyundai,SantroGLS
2842,Hyundai Santro GLS II - Euro II,Bangalore,2012,43000,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,3.25,13,Hyundai,SantroGLS
3272,BMW 5 Series 520d Sedan,Mumbai,2008,81000,Diesel,Automatic,Second,18.48 kmpl,NaN,NaN,NaN,NaN,10.50,17,BMW,5Series
3404,Maruti Swift 1.3 VXi,Jaipur,2006,125000,Petrol,Manual,Fourth & Above,16.1 kmpl,NaN,NaN,NaN,NaN,2.35,19,Maruti,Swift1.3
3520,BMW 5 Series 520d Sedan,Delhi,2012,90000,Diesel,Automatic,First,18.48 kmpl,NaN,NaN,NaN,NaN,14.50,13,BMW,5Series
3522,Hyundai Santro GLS II - Euro II,Kochi,2012,66400,Petrol,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,2.66,13,Hyundai,SantroGLS
3800,Ford Endeavour Hurricane LE,Mumbai,2012,129000,Diesel,Automatic,First,12.8 kmpl,2953 CC,null bhp,NaN,NaN,7.00,13,Ford,EndeavourHurricane
3810,Honda CR-V AT With Sun Roof,Kolkata,2013,27000,Petrol,Automatic,First,14.0 kmpl,NaN,NaN,NaN,NaN,11.99,12,Honda,CR-VAT
3882,Maruti Estilo LXI,Kolkata,2010,40000,Petrol,Manual,Second,19.5 kmpl,1061 CC,null bhp,NaN,NaN,2.50,15,Maruti,EstiloLXI
4011,Fiat Punto 1.3 Emotion,Pune,2011,45271,Diesel,Manual,First,20.3 kmpl,NaN,NaN,NaN,NaN,2.60,14,Fiat,Punto1.3
4152,Land Rover Range Rover 3.0 D,Mumbai,2003,75000,Diesel,Automatic,Second,0.0 kmpl,NaN,NaN,NaN,NaN,16.11,22,Land Rover,RoverRange
4229,Hyundai Santro Xing XG,Bangalore,2005,79000,Petrol,Manual,Second,17.0 kmpl,NaN,NaN,NaN,NaN,1.65,20,Hyundai,SantroXing
4577,BMW 5 Series 520d Sedan,Delhi,2012,72000,Diesel,Automatic,Third,18.48 kmpl,NaN,NaN,NaN,NaN,13.85,13,BMW,5Series
4604,Honda Jazz Select Edition,Pune,2011,98000,Petrol,Manual,First,16.7 kmpl,NaN,NaN,NaN,NaN,3.15,14,Honda,JazzSelect
4697,Fiat Punto 1.2 Dynamic,Kochi,2017,17941,Petrol,Manual,First,15.7 kmpl,NaN,NaN,NaN,NaN,3.93,8,Fiat,Punto1.2
4712,Hyundai Santro Xing XG,Pune,2003,80000,Petrol,Manual,Second,17.0 kmpl,NaN,NaN,NaN,NaN,0.90,22,Hyundai,SantroXing
4952,Fiat Punto 1.4 Emotion,Kolkata,2010,47000,Petrol,Manual,First,14.6 kmpl,NaN,NaN,NaN,NaN,1.49,15,Fiat,Punto1.4
5015,Maruti Swift 1.3 VXi,Delhi,2006,63000,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,1.60,19,Maruti,Swift1.3
5185,Maruti Swift 1.3 LXI,Delhi,2012,52000,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,3.65,13,Maruti,Swift1.3
5270,Honda City 1.5 GXI,Bangalore,2002,53000,Petrol,Manual,Second,0.0 kmpl,NaN,NaN,NaN,NaN,1.85,23,Honda,City1.5
5893,Maruti Estilo LXI,Chennai,2008,51000,Petrol,Manual,Second,19.5 kmpl,1061 CC,null bhp,NaN,NaN,1.75,17,Maruti,EstiloLXI
6042,Skoda Laura 1.8 TSI Ambition,Bangalore,2009,72000,Petrol,Manual,Second,17.5 kmpl,NaN,NaN,NaN,NaN,NaN,16,Skoda,Laura1.8
6541,Toyota Etios Liva Diesel TRD Sportivo,Bangalore,2012,56600,Diesel,Manual,First,23.59 kmpl,NaN,NaN,NaN,NaN,NaN,13,Toyota,EtiosLiva
6544,Hyundai i20 new Sportz AT 1.4,Bangalore,2012,58000,Petrol,Automatic,Second,15.0 kmpl,NaN,NaN,NaN,NaN,NaN,13,Hyundai,i20new
6633,Mahindra TUV 300 P4,Kolkata,2016,27000,Diesel,Manual,First,0.0 kmpl,NaN,NaN,NaN,NaN,NaN,9,Mahindra,TUV300
6643,BMW 5 Series 520d Sedan,Bangalore,2009,150000,Diesel,Automatic,Second,18.48 kmpl,NaN,NaN,NaN,NaN,NaN,16,BMW,5Series
6651,Maruti Swift 1.3 VXi,Kolkata,2015,36009,Petrol,Manual,First,16.1 kmpl,NaN,NaN,NaN,NaN,NaN,10,Maruti,Swift1.3
6677,Fiat Punto 1.4 Emotion,Jaipur,2010,65000,Petrol,Manual,Third,14.6 kmpl,NaN,NaN,NaN,NaN,NaN,15,Fiat,Punto1.4
6685,Maruti Swift 1.3 VXi,Pune,2010,115000,Petrol,Manual,Second,16.1 kmpl,NaN,NaN,NaN,NaN,NaN,15,Maruti,Swift1.3
6880,BMW 5 Series 520d Sedan,Chennai,2009,95000,Diesel,Automatic,Second,18.48 kmpl,NaN,NaN,NaN,NaN,NaN,16,BMW,5Series
6902,Toyota Etios Liva V,Kochi,2012,59311,Petrol,Manual,First,18.3 kmpl,NaN,NaN,NaN,NaN,NaN,13,Toyota,EtiosLiva
6957,Honda Jazz 2020 Petrol,Kochi,2019,11574,Petrol,Manual,First,0.0 kmpl,1199 CC,88.7 bhp,NaN,NaN,NaN,6,Honda,Jazz2020

In [56]:
temp_data[temp_data.Seats.isna()] = 2

In [57]:
temp_data.Seats.unique()

array([ 5.,  7.,  8.,  4.,  6.,  2., 10.,  9.])

In [58]:
temp_data.Seats.value_counts()

Seats
5.0     6047
7.0      796
8.0      170
4.0      119
2.0       72
6.0       38
10.0       8
9.0        3
Name: count, dtype: int64

In [59]:
temp_data.describe()

              Year  Kilometers_Driven        Seats        Price      Car_Age
count  7253.000000       7.253000e+03  7253.000000  6030.000000  7253.000000
mean   1998.693230       5.820014e+04     5.256032     9.436831    11.538674
std     171.352255       8.452090e+04     0.854206    11.176640     3.325560
min       2.000000       2.000000e+00     2.000000     0.440000     2.000000
25%    2011.000000       3.301600e+04     5.000000     3.490000     9.000000
50%    2014.000000       5.300000e+04     5.000000     5.600000    11.000000
75%    2016.000000       7.300000e+04     5.000000     9.897500    13.000000
max    2019.000000       6.500000e+06    10.000000   160.000000    29.000000

In [60]:
temp_data.Seats.dtypes

dtype('float64')

In [61]:
temp_data.Seats = temp_data.Seats.astype(int)

In [62]:
temp_data.Seats.dtypes

dtype('int64')

In [63]:
temp_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   object
 1   Location           7253 non-null   object
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   object
 5   Transmission       7253 non-null   object
 6   Owner_Type         7253 non-null   object
 7   Mileage            7251 non-null   object
 8   Engine             7253 non-null   object
 9   Power              7253 non-null   object
 10  Seats              7253 non-null   int64
 11  New_Price          1059 non-null   object
 12  Price              6030 non-null   float64
 13  Car_Age            7253 non-null   int64
 14  Brand              7253 non-null   object
 15  Model              7252 non-null   object
dtypes: float64(1), int64(4), object(11)
memory usage: 906.8+ KB

In [64]:
data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,10,Hyundai,Creta1.6
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,14,Honda,JazzV
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,12,Audi,A4New

In [65]:
data.New_Price.value_counts()

New_Price
95.13 Lakh    6
4.78 Lakh     6
33.36 Lakh    6
63.71 Lakh    6
20.74 Lakh    5
             ..
23.29 Lakh    1
13.08 Lakh    1
4.02 Lakh     1
66.71 Lakh    1
15.11 Lakh    1
Name: count, Length: 625, dtype: int64

In [66]:
data.New_Price.nunique()

625

In [67]:
data.shape

(7253, 16)

In [68]:
temp_data[temp_data.New_Price.isna()]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5,NaN,12.50,10,Hyundai,Creta1.6
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5,NaN,17.74,12,Audi,A4New
5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5,NaN,2.35,13,Hyundai,EONLPG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5,NaN,NaN,14,Volkswagen,VentoDiesel
7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5,NaN,NaN,10,Volkswagen,PoloGT
7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5,NaN,NaN,13,Nissan,MicraDiesel
7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5,NaN,NaN,12,Volkswagen,PoloGT
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5,NaN,NaN,11,Mercedes-Benz,E-Class2009-2013

In [69]:
temp_data.dtypes

Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                  int64
New_Price             object
Price                float64
Car_Age                int64
Brand                 object
Model                 object
dtype: object

In [70]:
temp_data.Fuel_Type.value_counts()

Fuel_Type
Diesel      3838
Petrol      3286
CNG           62
2             53
LPG           12
Electric       2
Name: count, dtype: int64

In [71]:
plt.figure(figsize=(12, 7))
sns.heatmap(temp_data.drop(['New_Price','Name','Location','Price'],axis=1).corr(), annot = True, vmin = -1, vmax = 1)
plt.show()

ValueError: could not convert string to float: 'CNG'

In [72]:
temp_data.Brand.value_counts()

Brand
Maruti           1428
Hyundai          1332
Honda             735
Toyota            504
Mercedes-Benz     380
Volkswagen        374
Ford              349
Mahindra          330
BMW               305
Audi              285
Tata              228
Skoda             201
Renault           170
Chevrolet         151
Nissan            117
Land Rover         64
2                  53
Jaguar             48
Mitsubishi         36
Fiat               34
Mini Cooper        31
Volvo              28
Porsche            19
Jeep               19
Datsun             17
Isuzu               5
Force               3
Bentley             2
Ambassador          1
Smart               1
Lamborghini         1
Hindustan           1
OpelCorsa           1
Name: count, dtype: int64

Maruti and Hyundai, disel and petrol - target

In [73]:
len(temp_data[temp_data["Brand"]=='Maruti'][temp_data["Fuel_Type"]=='Petrol'])

<ipython-input-73-f913318a77de>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(temp_data[temp_data["Brand"]=='Maruti'][temp_data["Fuel_Type"]=='Petrol'])

819

In [74]:
len(temp_data[temp_data["Brand"]=='Maruti'][temp_data["Fuel_Type"]=='Diesel'])

<ipython-input-74-859b4cbd4a8e>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(temp_data[temp_data["Brand"]=='Maruti'][temp_data["Fuel_Type"]=='Diesel'])

549

In [75]:
len(temp_data[(temp_data["Brand"]=='Maruti') & (temp_data["Fuel_Type"]!='Diesel') & (temp_data["Fuel_Type"]!='Petrol')])

60

In [76]:
len(temp_data[(temp_data["Brand"]=='Maruti') & (temp_data["Fuel_Type"]=='Diesel') & (temp_data["Fuel_Type"]=='Petrol')])

0

In [77]:
maruti = temp_data[(temp_data["Brand"]=='Maruti') & ((temp_data["Fuel_Type"]=='Petrol') | (temp_data["Fuel_Type"]=='Diesel'))]

In [78]:
maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7,NaN,6.00,13,Maruti,ErtigaVDI
10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5,10.65 Lakh,9.95,7,Maruti,CiazZeta
12,Maruti Swift VDI BSIV,Jaipur,2015,64424,Diesel,Manual,First,25.2 kmpl,1248 CC,74 bhp,5,NaN,5.60,10,Maruti,SwiftVDI
17,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5,NaN,5.99,8,Maruti,SwiftDDiS
21,Maruti S Cross DDiS 200 Alpha,Bangalore,2015,55392,Diesel,Manual,Second,23.65 kmpl,1248 CC,88.5 bhp,5,NaN,8.25,10,Maruti,SCross
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7210,Maruti Vitara Brezza VDi Option,Jaipur,2017,19000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,NaN,NaN,8,Maruti,VitaraBrezza
7218,Maruti Vitara Brezza ZDi Plus AMT,Mumbai,2018,3800,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5,12.46 Lakh,NaN,7,Maruti,VitaraBrezza
7220,Maruti Dzire AMT VDI,Delhi,2017,14300,Diesel,Automatic,First,28.4 kmpl,1248 CC,73.75 bhp,5,9.11 Lakh,NaN,8,Maruti,DzireAMT
7222,Maruti Celerio VXI AT,Chennai,2015,31717,Petrol,Automatic,First,23.1 kmpl,998 CC,67.04 bhp,5,NaN,NaN,10,Maruti,CelerioVXI
7235,Maruti Vitara Brezza ZDi,Kochi,2017,21380,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,10.57 Lakh,NaN,8,Maruti,VitaraBrezza

#..... need to add disel also, but in string form, ex: a + b

In [79]:
maruti

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7,NaN,6.00,13,Maruti,ErtigaVDI
10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5,10.65 Lakh,9.95,7,Maruti,CiazZeta
12,Maruti Swift VDI BSIV,Jaipur,2015,64424,Diesel,Manual,First,25.2 kmpl,1248 CC,74 bhp,5,NaN,5.60,10,Maruti,SwiftVDI
17,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5,NaN,5.99,8,Maruti,SwiftDDiS
21,Maruti S Cross DDiS 200 Alpha,Bangalore,2015,55392,Diesel,Manual,Second,23.65 kmpl,1248 CC,88.5 bhp,5,NaN,8.25,10,Maruti,SCross
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7210,Maruti Vitara Brezza VDi Option,Jaipur,2017,19000,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,NaN,NaN,8,Maruti,VitaraBrezza
7218,Maruti Vitara Brezza ZDi Plus AMT,Mumbai,2018,3800,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5,12.46 Lakh,NaN,7,Maruti,VitaraBrezza
7220,Maruti Dzire AMT VDI,Delhi,2017,14300,Diesel,Automatic,First,28.4 kmpl,1248 CC,73.75 bhp,5,9.11 Lakh,NaN,8,Maruti,DzireAMT
7222,Maruti Celerio VXI AT,Chennai,2015,31717,Petrol,Automatic,First,23.1 kmpl,998 CC,67.04 bhp,5,NaN,NaN,10,Maruti,CelerioVXI
7235,Maruti Vitara Brezza ZDi,Kochi,2017,21380,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5,10.57 Lakh,NaN,8,Maruti,VitaraBrezza

In [80]:
len(temp_data[temp_data["Brand"]=='Hyundai'][temp_data["Fuel_Type"]=='Petrol'])

<ipython-input-80-5ef9c209f835>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(temp_data[temp_data["Brand"]=='Hyundai'][temp_data["Fuel_Type"]=='Petrol'])

897

In [81]:
len(temp_data[temp_data["Brand"]=='Hyundai'][temp_data["Fuel_Type"]=='Diesel'])

<ipython-input-81-b4598829a9c6>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(temp_data[temp_data["Brand"]=='Hyundai'][temp_data["Fuel_Type"]=='Diesel'])

424

In [88]:
hyundai = temp_data[(temp_data["Brand"]=='Hyundai') & ((temp_data["Fuel_Type"]=='Petrol') | (temp_data["Fuel_Type"]=='Diesel'))]

Createing a dataframe for maruti with petrol and diesel

In [87]:
temp_data[temp_data['Kilometers_Driven']==6500000]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
2328,BMW X5 xDrive 30d M Sport,Chennai,2017,6500000,Diesel,Automatic,First,15.97 kmpl,2993 CC,258 bhp,5,NaN,65.0,8,BMW,X5xDrive

In [90]:
hyundai.describe()

              Year  Kilometers_Driven        Seats        Price      Car_Age
count  1321.000000        1321.000000  1321.000000  1091.000000  1321.000000
mean   2013.514005       51363.423164     5.028766     5.383905    11.485995
std       3.295083       34168.354019     0.238218     3.315572     3.295083
min    2001.000000        1000.000000     5.000000     0.450000     6.000000
25%    2012.000000       30529.000000     5.000000     3.105000     9.000000
50%    2014.000000       47200.000000     5.000000     4.650000    11.000000
75%    2016.000000       65461.000000     5.000000     6.500000    13.000000
max    2019.000000      620000.000000     7.000000    23.000000    24.000000

In [91]:
hyundai.isnull()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
1,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7234,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
7236,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
7242,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
7246,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
7247,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False

In [94]:
hyundai.to_csv('hyundai.csv')

In [95]:
maruti.to_csv("maruti.csv")

In [98]:
ProfileReport(hyundai,title = "Hyundai Report").to_file('hyundai_report.html')

/usr/local/lib/python3.11/dist-packages/ydata_profiling/utils/dataframe.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"index": "df_index"}, inplace=True)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]
 25%|██▌       | 4/16 [00:00<00:00, 38.20it/s]
 50%|█████     | 8/16 [00:00<00:00, 38.16it/s]
100%|██████████| 16/16 [00:00<00:00, 41.85it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [99]:
ProfileReport(maruti,title = "Maruti Report").to_file('maruti_report.html')

/usr/local/lib/python3.11/dist-packages/ydata_profiling/utils/dataframe.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"index": "df_index"}, inplace=True)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]
  6%|▋         | 1/16 [00:00<00:01,  9.58it/s]
 31%|███▏      | 5/16 [00:00<00:00, 25.54it/s]
 56%|█████▋    | 9/16 [00:00<00:00, 24.02it/s]
100%|██████████| 16/16 [00:00<00:00, 29.80it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [100]:
temp_data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Car_Age,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5,NaN,1.75,15,Maruti,WagonR
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5,NaN,12.50,10,Hyundai,Creta1.6
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5,8.61 Lakh,4.50,14,Honda,JazzV
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7,NaN,6.00,13,Maruti,ErtigaVDI
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5,NaN,17.74,12,Audi,A4New

maruti,hyundai, diesel, petrol,age,kilometer,transmission-maunaul, owner- first, mileage, engine,power,seat-5,price-missing??

kilometer range 50,000 - 55,000

In [105]:
kilometer_maruti = maruti[(maruti.Kilometers_Driven>=50000) & (maruti.Kilometers_Driven<=55000)]

In [109]:
kilometer_maruti.Mileage.replace('kmpl','',inplace=True)

<ipython-input-109-17cdac30260c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kilometer_maruti.Mileage.replace('kmpl','',inplace=True)

In [122]:
test = kilometer_maruti.Mileage.replace('18.9 kmpl','18.9') # remove all kmpl and other

In [123]:
test

27      20.92 kmpl
36       24.3 kmpl
51       22.9 kmpl
52       17.8 kmpl
119      24.3 kmpl
           ...
6823     19.7 kmpl
6934     19.0 kmpl
6968     15.0 kmpl
7085     20.4 kmpl
7101          18.9
Name: Mileage, Length: 111, dtype: object

In [124]:
test.unique()

array(['20.92 kmpl', '24.3 kmpl', '22.9 kmpl', '17.8 kmpl', '20.77 kmpl',
       '14.0 kmpl', '25.2 kmpl', '22.74 kmpl', '18.5 kmpl', '18.9',
       '28.4 kmpl', '20.51 kmpl', '21.4 kmpl', '26.59 kmpl', '16.1 kmpl',
       '23.1 kmpl', '28.09 kmpl', '15.1 kmpl', '21.5 kmpl', '20.73 kmpl',
       '18.6 kmpl', '17.5 kmpl', '23.4 kmpl', '22.5 kmpl', '19.0 kmpl',
       '19.12 kmpl', '24.52 kmpl', '19.7 kmpl', '15.5 kmpl', '24.07 kmpl',
       '25.47 kmpl', '15.9 kmpl', '27.39 kmpl', '20.4 kmpl', '17.3 kmpl',
       '16.02 kmpl', '24.7 kmpl', '19.1 kmpl', '19.3 kmpl', '15.0 kmpl'],
      dtype=object)

In [125]:
test.value_counts()

Mileage
18.9          10
16.1 kmpl      6
22.9 kmpl      5
20.77 kmpl     5
23.1 kmpl      5
25.2 kmpl      4
24.3 kmpl      4
20.92 kmpl     4
28.09 kmpl     4
19.0 kmpl      4
19.7 kmpl      4
28.4 kmpl      4
22.5 kmpl      3
22.74 kmpl     3
17.8 kmpl      3
18.6 kmpl      3
25.47 kmpl     3
19.12 kmpl     3
15.1 kmpl      3
17.5 kmpl      3
14.0 kmpl      2
26.59 kmpl     2
18.5 kmpl      2
20.51 kmpl     2
24.07 kmpl     2
15.5 kmpl      2
20.4 kmpl      2
20.73 kmpl     2
23.4 kmpl      1
21.5 kmpl      1
21.4 kmpl      1
24.52 kmpl     1
15.9 kmpl      1
27.39 kmpl     1
17.3 kmpl      1
16.02 kmpl     1
24.7 kmpl      1
19.1 kmpl      1
19.3 kmpl      1
15.0 kmpl      1
Name: count, dtype: int64